import { env } from "cloudflare:workers";
import { authorize } from "../../../../lib/authorization";
import { csvCell } from "../../../../lib/csv";

export const dynamic="force-dynamic";
export async function GET(){
  const auth=await authorize("students.export");if(!auth)return Response.json({error:"You do not have permission to export student data."},{status:403});
  const rows=await env.DB.prepare(`SELECT s.admission_number,s.first_name,s.last_name,s.preferred_name,s.gender,s.date_of_birth,s.blood_group,s.nationality,s.religion,s.national_id,s.place_of_birth,s.mother_tongue,s.domicile_district,s.identity_mark,s.admission_category,s.admission_source,s.previous_admission_number,s.phone,s.email,s.address_line1,s.address_line2,s.city,s.province,s.postal_code,s.emergency_contact_name,s.emergency_contact_phone,s.emergency_contact_relation,s.allergies,s.dietary_requirements,s.special_needs,s.accessibility_notes,s.doctor_name,s.doctor_phone,s.vaccination_notes,s.medical_notes,s.previous_school,s.previous_class,s.profile_notes,s.enrollment_status,s.admitted_on,c.code campus_code,c.name campus_name,y.name academic_year,cl.code class_code,cl.name class_name,se.code section_code,se.name section_name,e.roll_number FROM students s JOIN campuses c ON c.id=s.home_campus_id LEFT JOIN enrollments e ON e.student_id=s.id AND e.status='active' LEFT JOIN academic_years y ON y.id=e.academic_year_id LEFT JOIN classes cl ON cl.id=e.class_id LEFT JOIN sections se ON se.id=e.section_id WHERE s.organization_id=?1 ORDER BY s.first_name,s.last_name`).bind(auth.organizationId).all<Record<string,unknown>>();
  const headers=["admission_number","first_name","last_name","preferred_name","gender","date_of_birth","blood_group","nationality","religion","national_id","place_of_birth","mother_tongue","domicile_district","identity_mark","admission_category","admission_source","previous_admission_number","phone","email","address_line1","address_line2","city","province","postal_code","emergency_contact_name","emergency_contact_phone","emergency_contact_relation","allergies","dietary_requirements","special_needs","accessibility_notes","doctor_name","doctor_phone","vaccination_notes","medical_notes","previous_school","previous_class","profile_notes","enrollment_status","admitted_on","campus_code","campus_name","academic_year","class_code","class_name","section_code","section_name","roll_number"];
  const csv=[headers.join(","),...rows.results.map(row=>headers.map(header=>csvCell(row[header])).join(","))].join("\r\n");
  await env.DB.prepare("INSERT INTO audit_logs (id,organization_id,actor_user_id,action,entity_type,outcome,metadata_json) VALUES (?1,?2,?3,'student.bulk_export','students','success',?4)").bind(crypto.randomUUID(),auth.organizationId,auth.userId,JSON.stringify({count:rows.results.length})).run();
  return new Response(`\ufeff${csv}`,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":`attachment; filename="students-${new Date().toISOString().slice(0,10)}.csv"`,"cache-control":"private, no-store","x-content-type-options":"nosniff"}});
}
