import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { stripTypeScriptTypes } from 'node:module';
const root=new URL('../',import.meta.url);
const source=path=>readFileSync(new URL(path,root),'utf8');
const url=code=>'data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(code,{mode:'transform'})).toString('base64');
test('public applications persist pending approval with private photos; invalid scope and duplicate submissions are controlled',async()=>{
 const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const file of readdirSync(new URL('drizzle/',root)).filter(f=>f.endsWith('.sql')).sort())db.exec(source('drizzle/'+file));
 db.exec("INSERT INTO organizations(id,name,slug) VALUES ('org','The Mentor School','mentor'),('other','Other school','other'); INSERT INTO campuses(id,organization_id,name,code) VALUES ('campus','org','Main Campus','MAIN'),('foreign','other','Other campus','O'); INSERT INTO classes(id,organization_id,campus_id,name,code) VALUES ('class','org','campus','Grade 1','G1'),('foreign-class','other','foreign','Other class','G1'); INSERT INTO academic_years(id,organization_id,name,starts_on,ends_on,is_current) VALUES ('year','org','2026','2026-01-01','2026-12-31',1)");
 const objects=new Map();let auth=null,denyCampus=false;
 function prepare(sql){let args=[];return {bind(...v){args=v;return this},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return db.prepare(sql).run(...args)}}}
 globalThis.__publicTestEnv={DB:{prepare,async batch(statements){db.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());db.exec('COMMIT');return results}catch(e){db.exec('ROLLBACK');throw e}}},BUCKET:{async put(key,data){objects.set(key,data)},async delete(key){objects.delete(key)},async get(key){return objects.has(key)?{body:objects.get(key)}:null}}};
 globalThis.__publicTestAuth={authorize:async()=>auth,requireCampusAccess:async()=>denyCampus?new Response(null,{status:403}):null};
 const replaceEnv=s=>s.replace('import { env } from "cloudflare:workers";','const env = globalThis.__publicTestEnv;');
 const helper=url(replaceEnv(source('lib/public-forms.ts')));
 const endpoint=path=>import(url(replaceEnv(source(path)).replace(/from "(?:\.\.\/)+lib\/public-forms"/g,`from "${helper}"`).replace(/import \{ authorize, requireCampusAccess \} from "[^"]+";/,'const {authorize,requireCampusAccess}=globalThis.__publicTestAuth;')));
 const admission=await endpoint('app/api/public-admissions/route.ts');
 const config=await (await admission.GET()).json();assert.deepEqual(config.campuses.map(c=>c.id),['campus']);
 const id=crypto.randomUUID();
 const form=(extra={})=>{const f=new FormData();for(const [k,v] of Object.entries({submissionId:id,campusId:'campus',classId:'class',firstName:'Test',lastName:'Child',dateOfBirth:'2020-03-02',gender:'female',guardianName:'Test Parent',phone:'03001234567',address:'Test address',relationship:'Mother',consent:'on',...extra}))f.set(k,v);f.set('photo',new File([readFileSync(new URL('public/team/tahreem-tariq.jpeg',root))],'photo.jpg',{type:'image/jpeg'}));return f};
 const request=(body,origin='https://school.test')=>new Request('https://school.test/api/public-admissions',{method:'POST',headers:{origin,'cf-connecting-ip':'192.0.2.1'},body});
 let response=await admission.POST(request(form()));assert.equal(response.status,201,await response.clone().text());
 const app=db.prepare('SELECT * FROM admission_applications WHERE id=?').get(id);assert.equal(app.status,'submitted');assert.equal(app.campus_id,'campus');assert.equal(app.declaration_accepted,1);assert.equal(db.prepare('SELECT status FROM users WHERE id=?').get(app.created_by).status,'disabled');assert.equal(objects.size,1);
 assert.equal(db.prepare('SELECT verification_status FROM admission_documents WHERE application_id=?').get(id).verification_status,'pending');
 response=await admission.POST(request(form()));assert.equal(response.status,200);assert.equal(db.prepare('SELECT count(*) n FROM admission_applications').get().n,1);assert.equal(objects.size,1);
 assert.equal((await admission.POST(request(form({submissionId:crypto.randomUUID(),campusId:'foreign'})))).status,400);
 assert.equal((await admission.POST(request(form({submissionId:crypto.randomUUID(),classId:'foreign-class'})))).status,400);
 assert.equal((await admission.POST(request(form(),'https://evil.test'))).status,403);
 assert.equal((await admission.POST(new Request('https://school.test/api/public-admissions',{method:'POST',headers:{origin:'https://school.test','content-length':'7000000'},body:'x'}))).status,413);
 const photo=await endpoint('app/api/admissions/[id]/photo/route.ts');
 assert.equal((await photo.GET(new Request('https://school.test'),{params:Promise.resolve({id})})).status,403);
 auth={organizationId:'other'};assert.equal((await photo.GET(new Request('https://school.test'),{params:Promise.resolve({id})})).status,404);
 auth={organizationId:'org'};denyCampus=true;assert.equal((await photo.GET(new Request('https://school.test'),{params:Promise.resolve({id})})).status,403);
 denyCampus=false;response=await photo.GET(new Request('https://school.test'),{params:Promise.resolve({id})});assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'private, no-store');
 const feedback=await endpoint('app/api/parent-feedback/route.ts');const payload={id:crypto.randomUUID(),name:'Test Parent',message:'A helpful learning environment.',consent:true};
 response=await feedback.POST(request(JSON.stringify(payload)));assert.equal(response.status,200);const list=await (await feedback.GET()).json();assert.equal(list.feedback.length,1);assert.equal(list.feedback[0].message,payload.message);
 await feedback.POST(request(JSON.stringify(payload)));assert.equal(db.prepare('SELECT count(*) n FROM parent_feedback').get().n,1);
 for(let i=0;i<3;i++)await feedback.POST(request(JSON.stringify({...payload,id:crypto.randomUUID()})));
 assert.equal((await feedback.POST(request(JSON.stringify({...payload,id:crypto.randomUUID()})))).status,429);
 db.close();delete globalThis.__publicTestEnv;delete globalThis.__publicTestAuth;
});
