import { env } from "cloudflare:workers";
import { authorize, requireCampusAccess } from "../../../../lib/authorization";
import { enforceRateLimit, requireSameOrigin, safeMetadata } from "../../../../lib/security";

export const dynamic="force-dynamic";
const clean=(value:unknown,length=300)=>typeof value==="string"?value.trim().slice(0,length):"";
const datePattern=/^\d{4}-\d{2}-\d{2}$/;
const statuses=new Set(["present","absent","late","leave","half_day"]);

async function linkedStudentIds(auth:NonNullable<Awaited<ReturnType<typeof authorize>>>){
  if(auth.permissions.has("students.view"))return null;
  const rows=await env.DB.prepare(`SELECT DISTINCT s.id FROM students s LEFT JOIN student_guardians sg ON sg.student_id=s.id LEFT JOIN guardians g ON g.id=sg.guardian_id AND g.organization_id=s.organization_id WHERE s.organization_id=?1 AND (lower(s.email)=lower(?2) OR lower(g.email)=lower(?2))`).bind(auth.organizationId,auth.email).all<{id:string}>();
  return new Set(rows.results.map(row=>row.id));
}

export async function GET(request:Request){
  const auth=await authorize("student_attendance.report");if(!auth)return Response.json({error:"You do not have permission to view attendance reports."},{status:403});
  const url=new URL(request.url),now=new Date(),monthStart=`${now.toISOString().slice(0,7)}-01`,from=clean(url.searchParams.get("from"),10)||monthStart,to=clean(url.searchParams.get("to"),10)||now.toISOString().slice(0,10),campusId=clean(url.searchParams.get("campusId"))||auth.activeCampusId||"",classId=clean(url.searchParams.get("classId")),sectionId=clean(url.searchParams.get("sectionId"));
  if(!datePattern.test(from)||!datePattern.test(to)||from>to)return Response.json({error:"Select a valid report period."},{status:400});
  if(campusId){const denied=await requireCampusAccess(auth,campusId,"student.attendance.report");if(denied)return denied;}
  const linked=await linkedStudentIds(auth),linkedIds=linked?[...linked]:[],studentFilter=linked?linkedIds.length?` AND r.student_id IN (${linkedIds.map((_,index)=>`?${index+7}`).join(",")})`:" AND 1=0":"";
  const bindings=[auth.organizationId,from,to,campusId,classId,sectionId,...linkedIds];
  const [daily,students,records,corrections,alerts,campuses,classes,sections]=await Promise.all([
    env.DB.prepare(`SELECT r.attendance_date,count(*) total,sum(r.status='present') present,sum(r.status='absent') absent,sum(r.status='late') late,sum(r.status='leave') leave_count,sum(r.status='half_day') half_day FROM student_attendance_records r JOIN enrollments e ON e.id=r.enrollment_id WHERE r.organization_id=?1 AND r.attendance_date BETWEEN ?2 AND ?3 AND (?4='' OR e.campus_id=?4) AND (?5='' OR e.class_id=?5) AND (?6='' OR e.section_id=?6)${studentFilter} GROUP BY r.attendance_date ORDER BY r.attendance_date`).bind(...bindings).all(),
    env.DB.prepare(`SELECT s.id,s.admission_number,s.first_name,s.last_name,e.roll_number,c.name class_name,se.name section_name,count(*) total,sum(r.status='present') present,sum(r.status='absent') absent,sum(r.status='late') late,sum(r.status='leave') leave_count,sum(r.status='half_day') half_day,round(100.0*(sum(r.status='present')+0.5*sum(r.status IN ('late','half_day')))/count(*),1) attendance_percentage FROM student_attendance_records r JOIN students s ON s.id=r.student_id AND s.organization_id=r.organization_id JOIN enrollments e ON e.id=r.enrollment_id LEFT JOIN classes c ON c.id=e.class_id LEFT JOIN sections se ON se.id=e.section_id WHERE r.organization_id=?1 AND r.attendance_date BETWEEN ?2 AND ?3 AND (?4='' OR e.campus_id=?4) AND (?5='' OR e.class_id=?5) AND (?6='' OR e.section_id=?6)${studentFilter} GROUP BY s.id,s.admission_number,s.first_name,s.last_name,e.roll_number,c.name,se.name ORDER BY attendance_percentage,s.first_name`).bind(...bindings).all(),
    env.DB.prepare(`SELECT r.id,r.attendance_date,r.status,r.remarks,s.admission_number,s.first_name,s.last_name,c.name class_name,se.name section_name FROM student_attendance_records r JOIN students s ON s.id=r.student_id AND s.organization_id=r.organization_id JOIN enrollments e ON e.id=r.enrollment_id LEFT JOIN classes c ON c.id=e.class_id LEFT JOIN sections se ON se.id=e.section_id WHERE r.organization_id=?1 AND r.attendance_date BETWEEN ?2 AND ?3 AND (?4='' OR e.campus_id=?4) AND (?5='' OR e.class_id=?5) AND (?6='' OR e.section_id=?6)${studentFilter} ORDER BY r.attendance_date DESC,s.first_name LIMIT 200`).bind(...bindings).all(),
    auth.permissions.has("student_attendance.approve_correction")?env.DB.prepare(`SELECT q.*,r.attendance_date,r.status current_status,s.admission_number,s.first_name,s.last_name,c.name class_name,se.name section_name,u.display_name requested_by_name FROM student_attendance_correction_requests q JOIN student_attendance_records r ON r.id=q.attendance_record_id AND r.organization_id=q.organization_id JOIN students s ON s.id=r.student_id JOIN enrollments e ON e.id=r.enrollment_id LEFT JOIN classes c ON c.id=e.class_id LEFT JOIN sections se ON se.id=e.section_id JOIN users u ON u.id=q.requested_by WHERE q.organization_id=?1 AND (?2='' OR q.campus_id=?2) ORDER BY q.status='pending' DESC,q.created_at DESC LIMIT 50`).bind(auth.organizationId,campusId).all():Promise.resolve({results:[]}),
    auth.permissions.has("student_attendance.alerts")?env.DB.prepare(`SELECT a.id,a.alert_type,a.status,a.recipient_count,a.created_at,s.admission_number,s.first_name,s.last_name,r.attendance_date FROM attendance_alerts a JOIN students s ON s.id=a.student_id JOIN student_attendance_records r ON r.id=a.attendance_record_id WHERE a.organization_id=?1 AND (?2='' OR a.campus_id=?2) ORDER BY a.created_at DESC LIMIT 50`).bind(auth.organizationId,campusId).all():Promise.resolve({results:[]}),
    env.DB.prepare("SELECT id,name FROM campuses WHERE organization_id=?1 AND status='active' AND (?2='' OR id=?2) ORDER BY is_main DESC,name").bind(auth.organizationId,campusId).all(),
    env.DB.prepare("SELECT id,name,campus_id FROM classes WHERE organization_id=?1 AND status='active' AND (?2='' OR campus_id IS NULL OR campus_id=?2) ORDER BY sort_order,name").bind(auth.organizationId,campusId).all(),
    env.DB.prepare("SELECT id,name,class_id,campus_id FROM sections WHERE organization_id=?1 AND status='active' AND (?2='' OR campus_id=?2) ORDER BY name").bind(auth.organizationId,campusId).all(),
  ]);
  return Response.json({from,to,campuses:campuses.results,classes:classes.results,sections:sections.results,daily:daily.results,students:students.results,records:records.results,correctionRequests:corrections.results,alerts:alerts.results,linkedOnly:linked!==null,canRequest:auth.permissions.has("student_attendance.request_correction"),canApprove:auth.permissions.has("student_attendance.approve_correction"),minimumAttendance:85},{headers:{"cache-control":"private, no-store"}});
}

export async function POST(request:Request){
  const origin=requireSameOrigin(request);if(origin)return origin;
  const body=await request.json().catch(()=>null) as Record<string,unknown>|null,action=clean(body?.action,30),auth=await authorize(action==="review_correction"?"student_attendance.approve_correction":"student_attendance.request_correction");if(!auth)return Response.json({error:"You do not have permission for this correction workflow."},{status:403});
  if(!await enforceRateLimit(auth,"student.attendance.correction",20,300))return Response.json({error:"Correction request limit reached."},{status:429});
  if(action==="request_correction"){
    const recordId=clean(body?.attendanceRecordId),requestedStatus=clean(body?.requestedStatus,20),reason=clean(body?.reason,500);if(!recordId||!statuses.has(requestedStatus)||reason.length<5)return Response.json({error:"Select a status and explain the correction."},{status:400});
    const record=await env.DB.prepare(`SELECT r.id,r.student_id,e.campus_id FROM student_attendance_records r JOIN enrollments e ON e.id=r.enrollment_id WHERE r.id=?1 AND r.organization_id=?2`).bind(recordId,auth.organizationId).first<{id:string;student_id:string;campus_id:string}>();if(!record)return Response.json({error:"Attendance record not found."},{status:404});
    const denied=await requireCampusAccess(auth,record.campus_id,"student.attendance.correction.request");if(denied)return denied;
    const linked=await linkedStudentIds(auth);if(linked&&!linked.has(record.student_id))return Response.json({error:"You may only request corrections for your linked student record."},{status:403});
    const id=crypto.randomUUID();try{await env.DB.batch([env.DB.prepare("INSERT INTO student_attendance_correction_requests (id,organization_id,campus_id,attendance_record_id,requested_status,reason,status,requested_by) VALUES (?1,?2,?3,?4,?5,?6,'pending',?7)").bind(id,auth.organizationId,record.campus_id,recordId,requestedStatus,reason,auth.userId),env.DB.prepare("INSERT INTO audit_logs (id,organization_id,campus_id,actor_user_id,action,entity_type,entity_id,outcome,metadata_json) VALUES (?1,?2,?3,?4,'student.attendance.correction.request','attendance_correction_request',?5,'success',?6)").bind(crypto.randomUUID(),auth.organizationId,record.campus_id,auth.userId,id,safeMetadata({recordId,requestedStatus}))]);return Response.json({ok:true,id});}catch{return Response.json({error:"A correction request is already pending for this record."},{status:409});}
  }
  if(action==="review_correction"){
    const requestId=clean(body?.requestId),decision=clean(body?.decision,20),notes=clean(body?.notes,500);if(!requestId||!["approve","reject"].includes(decision))return Response.json({error:"Select an approval decision."},{status:400});
    const row=await env.DB.prepare(`SELECT q.*,r.session_id,r.status current_status,r.remarks current_remarks FROM student_attendance_correction_requests q JOIN student_attendance_records r ON r.id=q.attendance_record_id AND r.organization_id=q.organization_id WHERE q.id=?1 AND q.organization_id=?2`).bind(requestId,auth.organizationId).first<Record<string,unknown>>();if(!row||row.status!=="pending")return Response.json({error:"Only pending requests can be reviewed."},{status:409});
    const denied=await requireCampusAccess(auth,String(row.campus_id),"student.attendance.correction.review");if(denied)return denied;
    const statements=[env.DB.prepare("UPDATE student_attendance_correction_requests SET status=?1,reviewed_by=?2,review_notes=?3,reviewed_at=unixepoch()*1000,updated_at=unixepoch()*1000 WHERE id=?4 AND organization_id=?5").bind(decision==="approve"?"approved":"rejected",auth.userId,notes||null,requestId,auth.organizationId)];
    if(decision==="approve")statements.push(env.DB.prepare("INSERT INTO student_attendance_corrections (id,organization_id,attendance_record_id,previous_status,new_status,previous_remarks,new_remarks,reason,corrected_by) VALUES (?1,?2,?3,?4,?5,?6,?6,?7,?8)").bind(crypto.randomUUID(),auth.organizationId,row.attendance_record_id,row.current_status,row.requested_status,row.current_remarks,row.reason,auth.userId),env.DB.prepare("UPDATE student_attendance_records SET status=?1,updated_at=unixepoch()*1000 WHERE id=?2 AND organization_id=?3").bind(row.requested_status,row.attendance_record_id,auth.organizationId),env.DB.prepare("UPDATE student_attendance_sessions SET present_count=(SELECT count(*) FROM student_attendance_records WHERE session_id=?1 AND status='present'),absent_count=(SELECT count(*) FROM student_attendance_records WHERE session_id=?1 AND status='absent'),late_count=(SELECT count(*) FROM student_attendance_records WHERE session_id=?1 AND status='late'),leave_count=(SELECT count(*) FROM student_attendance_records WHERE session_id=?1 AND status='leave'),half_day_count=(SELECT count(*) FROM student_attendance_records WHERE session_id=?1 AND status='half_day'),updated_at=unixepoch()*1000 WHERE id=?1 AND organization_id=?2").bind(row.session_id,auth.organizationId));
    statements.push(env.DB.prepare("INSERT INTO audit_logs (id,organization_id,campus_id,actor_user_id,action,entity_type,entity_id,outcome,metadata_json) VALUES (?1,?2,?3,?4,'student.attendance.correction.review','attendance_correction_request',?5,'success',?6)").bind(crypto.randomUUID(),auth.organizationId,row.campus_id,auth.userId,requestId,safeMetadata({decision,requestedStatus:row.requested_status})));
    await env.DB.batch(statements);return Response.json({ok:true});
  }
  return Response.json({error:"Invalid correction action."},{status:400});
}
