"use client";
import { FormEvent, useEffect, useState } from "react";

type Option={id:string;name:string;is_current?:number};
type Report={summary:{total?:number;submitted?:number;approved?:number;rejected?:number;enrolled?:number};statuses:Array<{label:string;value:number}>;campuses:Array<{label:string;value:number;enrolled:number}>;classes:Array<{label:string;value:number;enrolled:number}>;applications:Array<Record<string,string|number|null>>};
const empty:Report={summary:{},statuses:[],campuses:[],classes:[],applications:[]};

export default function AdmissionReportsPanel({campuses,academicYears}:{campuses:Option[];academicYears:Option[]}){
  const [report,setReport]=useState<Report>(empty),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
  async function load(params=""){setLoading(true);setError("");const response=await fetch(`/api/admissions/reports${params?`?${params}`:""}`,{cache:"no-store"}),body=await response.json();setLoading(false);if(response.ok){setReport(body);setQuery(params)}else setError(body.error??"Could not load admission reporting.");}
  useEffect(()=>{let active=true;fetch("/api/admissions/reports",{cache:"no-store"}).then(response=>Promise.all([response,response.json()])).then(([response,body])=>{if(!active)return;setLoading(false);if(response.ok)setReport(body);else setError(body.error??"Could not load admission reporting.")}).catch(()=>{if(active){setLoading(false);setError("Could not load admission reporting.")}});return()=>{active=false}},[]);
  function filter(event:FormEvent<HTMLFormElement>){event.preventDefault();const params=new URLSearchParams();for(const [key,value] of new FormData(event.currentTarget).entries())if(value)params.set(key,String(value));void load(params.toString());}
  const conversion=report.summary.total?Math.round((Number(report.summary.enrolled??0)/Number(report.summary.total))*100):0;
  return <div className="admission-reports">
    <form className="report-filters" onSubmit={filter}><label>Campus<select name="campusId"><option value="">All campuses</option>{campuses.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><label>Academic year<select name="academicYearId"><option value="">All years</option>{academicYears.map(v=><option value={v.id} key={v.id}>{v.name}{v.is_current?" · Current":""}</option>)}</select></label><label>Status<select name="status"><option value="">All statuses</option><option value="draft">Draft</option><option value="submitted">Submitted</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="enrolled">Enrolled</option></select></label><label>From<input type="date" name="from"/></label><label>To<input type="date" name="to"/></label><button disabled={loading}>{loading?"Loading…":"Apply filters"}</button><a href={`/api/admissions/reports?${query}${query?"&":""}format=csv`}>⇩ Export CSV</a></form>
    {error&&<p className="access-message">{error}</p>}
    <div className="report-kpis"><article><span>📋</span><small>Applications</small><strong>{report.summary.total??0}</strong></article><article><span>🕒</span><small>Submitted</small><strong>{report.summary.submitted??0}</strong></article><article><span>✅</span><small>Approved</small><strong>{report.summary.approved??0}</strong></article><article><span>🎓</span><small>Enrolled</small><strong>{report.summary.enrolled??0}</strong></article><article><span>📈</span><small>Conversion</small><strong>{conversion}%</strong></article></div>
    <div className="report-insights"><section><header><div><span>◎</span><div><h3>Application pipeline</h3><p>Status distribution for the selected period</p></div></div></header><div className="pipeline-bars">{report.statuses.length?report.statuses.map(v=>{const pct=Math.round((v.value/Math.max(1,Number(report.summary.total)))*100);return <div key={v.label}><span><b>{v.label.replaceAll("_"," ")}</b><em>{v.value} · {pct}%</em></span><i><u style={{width:`${pct}%`}}/></i></div>}):<p>No applications match these filters.</p>}</div></section><section><header><div><span>🏫</span><div><h3>Campus performance</h3><p>Applications and completed enrollments</p></div></div></header><div className="report-ranking">{report.campuses.map(v=><div key={v.label}><strong>{v.label}</strong><span>{v.value} applications</span><b>{v.enrolled} enrolled</b></div>)}</div></section><section><header><div><span>📚</span><div><h3>Class demand</h3><p>Most requested classes</p></div></div></header><div className="report-ranking">{report.classes.map(v=><div key={v.label}><strong>{v.label}</strong><span>{v.value} applications</span><b>{v.enrolled} enrolled</b></div>)}</div></section></div>
    <section className="report-register"><header><div><h3>Admission register</h3><p>{report.applications.length} matching applications</p></div><button type="button" onClick={()=>window.print()}>🖨 Print report</button></header><div className="report-table"><div className="report-row report-head"><span>Application</span><span>Student</span><span>Campus / class</span><span>Status</span><span>Fee package</span></div>{report.applications.map((v,index)=><div className="report-row" key={String(v.application_number??index)}><span><strong>{String(v.application_number??"")}</strong><small>{String(v.submitted_on??"Not submitted")}</small></span><span><strong>{String(v.child_first_name??"")} {String(v.child_last_name??"")}</strong><small>{String(v.guardian_name??"")} · {String(v.primary_phone??"")}</small></span><span><strong>{String(v.campus_name??"")}</strong><small>{String(v.class_name??"Class not selected")}</small></span><span><b className="status-pill">{String(v.status??"").replaceAll("_"," ")}</b></span><span><strong>{String(v.fee_package_name??"Not assigned")}</strong><small>{v.admission_number?`Admission ${v.admission_number}`:""}</small></span></div>)}</div></section>
  </div>;
}
