"use client";import{useEffect,useState}from"react";
type Data={campus:string;students:number;staff:number;attendanceRate:number;fees:{billed:number;paid:number;balance:number};results:{average:number|null;results:number};operations:{total:number;active:number};classes:Array<{name:string;students:number}>;canExport:boolean;generatedAt:number};
const money=(n:number)=>new Intl.NumberFormat("en-PK",{style:"currency",currency:"PKR",maximumFractionDigits:0}).format(n);
async function readJson(response:Response){
 const body=await response.text();
 if(!body.trim())throw Error("Analytics is temporarily unavailable. Please try again.");
 try{return JSON.parse(body) as Data&{error?:string}}catch{throw Error("Analytics returned an invalid response. Please try again.")}
}
export default function AnalyticsPanel(){const[d,setD]=useState<Data|null>(null),[error,setError]=useState("");useEffect(()=>{fetch("/api/analytics",{cache:"no-store"}).then(async r=>{const j=await readJson(r);if(!r.ok)throw Error(j.error||"Analytics could not be loaded.");setD(j)}).catch(e=>setError(e instanceof Error?e.message:"Analytics could not be loaded."))},[]);if(!d)return <p className="analytics-state">{error||"Loading school analytics…"}</p>;const max=Math.max(1,...d.classes.map(x=>x.students));return <section className="analytics-shell"><header className="analytics-hero"><div><span>PHASE 13 · ADVANCED ANALYTICS & REPORTING</span><h1>Leadership Intelligence</h1><p>{d.campus} · A connected view of enrollment, people, learning, finance and operations.</p></div>{d.canExport&&<a href="/api/analytics?format=csv">Export CSV</a>}</header><div className="analytics-kpis"><article><i>🎓</i><b>{d.students}</b><small>Active students</small></article><article><i>🪪</i><b>{d.staff}</b><small>Active staff</small></article><article><i>📅</i><b>{d.attendanceRate}%</b><small>Attendance rate</small></article><article><i>🏅</i><b>{d.results.average||0}%</b><small>Average result</small></article></div><div className="analytics-grid"><article className="analytics-card"><header><h2>Enrollment by class</h2><span>{d.classes.length} classes</span></header><div className="analytics-bars">{d.classes.length?d.classes.map(x=><div key={x.name}><label><span>{x.name}</span><b>{x.students}</b></label><i><em style={{width:`${x.students/max*100}%`}}/></i></div>):<p>No active class enrollments.</p>}</div></article><article className="analytics-card"><header><h2>Financial collection</h2><span>{d.fees.billed?Math.round(d.fees.paid*100/d.fees.billed):0}% collected</span></header><div className="analytics-money"><div><span>Billed</span><b>{money(d.fees.billed)}</b></div><div><span>Collected</span><b>{money(d.fees.paid)}</b></div><div><span>Outstanding</span><b>{money(d.fees.balance)}</b></div></div></article><article className="analytics-card analytics-wide"><header><h2>Operational health</h2><span>Live register summary</span></header><div className="analytics-health"><div><b>{d.operations.total}</b><span>Total operational records</span></div><div><b>{d.operations.active||0}</b><span>Active workflows</span></div><div><b>{d.results.results}</b><span>Published/approved results</span></div><div><b>{new Date(d.generatedAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</b><span>Report refreshed</span></div></div></article></div></section>}
