"use client";
import type { AccessData } from "./AccessControlPanel";
import type { ConfigurationData } from "./ConfigurationPanel";
import type { SecurityData } from "./SecurityPanel";
import type { StudentDirectoryData } from "./StudentDirectoryPanel";
import { cn } from "./ui/TailwindPrimitives";

export default function HomeDashboardPanel({schoolName,userName,accessData,configurationData,securityData,studentData,onNavigate}:{schoolName:string;userName:string;accessData:AccessData|null;configurationData:ConfigurationData|null;securityData:SecurityData|null;studentData:StudentDirectoryData|null;onNavigate:(view:string)=>void}){
  const first=userName.split(/\s+/)[0]||"Administrator",currentYear=configurationData?.academicYears.find(y=>y.is_current);
  const cards=[
    ["🎓","Current students",studentData?.summary.active??0,"Student records","Students"],
    ["🏫","School campuses",configurationData?.campuses.filter(c=>c.status==="active").length??0,"Active locations","Configuration"],
    ["👥","Users & staff",accessData?.users.filter(u=>u.status==="active").length??0,"Active accounts","Access Control"],
    ["📅","Academic year",currentYear?.name??"Not set",currentYear?`${currentYear.starts_on} – ${currentYear.ends_on}`:"Configuration required","Configuration"],
  ] as const;
  const campusCounts=(studentData?.campuses??[]).map((campus,index)=>({name:campus.name,count:studentData?.students.filter(s=>s.campus_name===campus.name).length??0,color:["purple","green","yellow","coral"][index%4]}));
  const total=Math.max(1,campusCounts.reduce((sum,c)=>sum+c.count,0));
  const panel="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";
  const header="mb-5 flex items-start justify-between gap-4 [&_h2]:text-lg [&_h2]:font-extrabold [&_h2]:text-slate-950 [&_p]:mt-1 [&_p]:text-sm [&_p]:text-slate-500 [&_button]:text-sm [&_button]:font-bold [&_button]:text-red-600";
  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-5"><div><span className="text-xs font-black uppercase tracking-[.18em] text-red-600">SCHOOL MANAGEMENT OVERVIEW</span><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Good morning, {first}! 👋</h1><p className="mt-2 text-sm text-slate-600">Here’s what’s happening at {schoolName} today.</p></div><button className="rounded-xl bg-red-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-red-500" onClick={()=>onNavigate("Students")}>＋ Add student</button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([icon,label,value,detail,view],index)=><button className="relative grid min-h-36 grid-cols-[48px_1fr] gap-x-3 rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md" key={label} onClick={()=>onNavigate(view)}><span className={cn("row-span-2 grid h-12 w-12 place-items-center rounded-xl text-xl",["bg-violet-100","bg-emerald-100","bg-amber-100","bg-rose-100"][index])}>{icon}</span><small className="self-end text-xs font-semibold text-slate-500">{label}</small><strong className="truncate text-2xl font-black text-slate-950">{value}</strong><em className="col-span-2 mt-3 text-xs not-italic text-slate-500">{detail}</em></button>)}</div>
    <div className="grid gap-5 xl:grid-cols-2">
      <section className={panel}><header className={header}><div><h2>Campus overview</h2><p>Current students across active campuses</p></div><button onClick={()=>onNavigate("Students")}>View directory</button></header>{campusCounts.length?<div className="flex flex-col items-center gap-6 py-3 sm:flex-row"><div className="grid h-40 w-40 shrink-0 place-items-center rounded-full" style={{background:`conic-gradient(#7658e8 0 42%,#40b780 42% 70%,#f2b834 70% 86%,#ef7774 86% 100%)`}}><span className="grid h-24 w-24 place-items-center rounded-full bg-white text-center"><strong className="block text-2xl font-black">{studentData?.summary.active??0}</strong><small className="block text-xs text-slate-500">Students</small></span></div><div className="grid w-full gap-3">{campusCounts.map((c,index)=><div className="grid grid-cols-[12px_1fr_auto_auto] items-center gap-3 text-sm" key={c.name}><span className={cn("h-3 w-3 rounded-full",["bg-violet-500","bg-emerald-500","bg-amber-500","bg-rose-500"][index%4])}/><strong>{c.name}</strong><b>{c.count}</b><small className="text-slate-500">{Math.round(c.count/total*100)}%</small></div>)}</div></div>:<div className="rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">No campus data available.</div>}</section>
      <section className={panel}><header className={header}><div><h2>Recent activity</h2><p>Latest protected operations</p></div><button onClick={()=>onNavigate("Security & Audit")}>View all</button></header><div className="divide-y divide-slate-100">{securityData?.logs.slice(0,5).map((log,index)=><article className="flex items-center gap-3 py-3" key={log.id}><span className={cn("grid h-10 w-10 shrink-0 place-items-center rounded-xl",["bg-violet-100","bg-emerald-100","bg-amber-100","bg-rose-100"][index%4])}>{log.action.includes("student")?"🎓":log.action.includes("campus")?"🏫":log.action.includes("user")?"👤":"🛡️"}</span><div className="min-w-0 flex-1"><strong className="block truncate text-sm capitalize">{log.action.replaceAll("."," ")}</strong><small className="block truncate text-xs text-slate-500">{log.actor_name??"System"} · {log.campus_name??"School-wide"}</small></div><time className="text-xs text-slate-400">{new Date(log.created_at).toLocaleDateString()}</time></article>)}{!securityData?.logs.length&&<div className="rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">Activity will appear here as your team uses the system.</div>}</div></section>
      <section className={cn(panel,"xl:col-span-2")}><header className={header}><div><h2>Foundation progress</h2><p>Your SMS implementation roadmap</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Phase 8C</span></header><div className="grid gap-4 md:grid-cols-2">{[["🛡️","Secure foundation","Authentication, RBAC, audit and backup","100%"],["🎓","Student Information System","Operational school modules through result publication","92%"]].map(([icon,title,detail,progress])=><article className="flex items-center gap-4 rounded-xl border border-slate-100 bg-slate-50 p-4" key={title}><span className="text-2xl">{icon}</span><div className="min-w-0 flex-1"><strong className="block text-sm">{title}</strong><small className="block text-xs text-slate-500">{detail}</small><i className="mt-3 block h-2 overflow-hidden rounded-full bg-slate-200"><b className="block h-full rounded-full bg-red-500" style={{width:progress}}/></i></div><em className="text-sm font-black not-italic">{progress}</em></article>)}</div></section>
      <aside className="flex items-center gap-4 rounded-2xl border border-amber-200 bg-amber-50 p-5 xl:col-span-2"><span className="text-2xl">💡</span><div className="flex-1"><strong className="text-sm text-amber-950">Smart setup tip</strong><p className="mt-1 text-sm text-amber-800">{currentYear?"Your current academic year is ready. Add classes before assigning new students.":"Set the current academic year before assigning students to classes."}</p></div><button className="rounded-lg bg-amber-900 px-3 py-2 text-xs font-bold text-white" onClick={()=>onNavigate("Configuration")}>Configure</button></aside>
    </div>
  </div>;
}
