"use client";
import type { AccessData } from "./AccessControlPanel";
import type { ConfigurationData } from "./ConfigurationPanel";
import type { SecurityData } from "./SecurityPanel";
import type { StudentDirectoryData } from "./StudentDirectoryPanel";

const accents=["#8b5cf6","#22c55e","#f97316","#d946ef"];
const sparkPaths=["M2 38 C14 30 20 34 31 25 S48 36 61 23 S80 29 91 18 S108 25 126 8","M2 35 C17 40 25 22 39 29 S58 19 72 25 S91 12 105 21 S117 12 126 9","M2 38 C17 32 24 36 38 26 S58 31 70 20 S89 28 103 16 S117 18 126 11","M2 37 C16 26 28 35 41 24 S60 30 74 19 S91 25 105 14 S118 19 126 8"];

function Sparkline({index}:{index:number}) { const color=accents[index]; return <svg aria-hidden="true" className="mt-2 h-10 w-full" viewBox="0 0 128 44" preserveAspectRatio="none"><defs><linearGradient id={`spark-${index}`} x1="0" y1="0" x2="0" y2="1"><stop stopColor={color} stopOpacity=".35"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient></defs><path d={`${sparkPaths[index]} L126 44 L2 44 Z`} fill={`url(#spark-${index})`}/><path d={sparkPaths[index]} fill="none" stroke={color} strokeWidth="2" strokeLinecap="round"/></svg>; }

export default function HomeDashboardPanel({schoolName,userName,accessData,configurationData,securityData,studentData,onNavigate}:{schoolName:string;userName:string;accessData:AccessData|null;configurationData:ConfigurationData|null;securityData:SecurityData|null;studentData:StudentDirectoryData|null;onNavigate:(view:string)=>void}) {
  const first=userName.split(/\s+/)[0]||"Administrator";
  const currentYear=configurationData?.academicYears.find(year=>year.is_current);
  const activeStudents=studentData?.summary.active??0;
  const activeCampuses=configurationData?.campuses.filter(campus=>campus.status==="active").length??0;
  const activeUsers=accessData?.users.filter(user=>user.status==="active").length??0;
  const metrics=[["Current students",activeStudents,"Active enrolments","🎓","Students"],["School campuses",activeCampuses,"Active locations","🏫","Configuration"],["Users & staff",activeUsers,"Active accounts","👥","Access Control"],["Academic year",currentYear?.name??"Not set","Current session","📅","Configuration"]] as const;
  const campusCounts=(studentData?.campuses??[]).map((campus,index)=>({name:campus.name,count:studentData?.students.filter(student=>student.campus_name===campus.name).length??0,color:accents[index%accents.length]}));
  const maxCampus=Math.max(1,...campusCounts.map(campus=>campus.count));
  const total=Math.max(1,campusCounts.reduce((sum,campus)=>sum+campus.count,0));
  const panel="rounded-2xl border border-white/[.08] bg-[#090d1d]/95 shadow-[0_12px_34px_rgba(0,0,0,.22)]";
  const panelHeader="flex items-center justify-between border-b border-white/[.06] px-4 py-3";
  return <div className="w-full space-y-3.5">
    <header className="flex flex-wrap items-center justify-between gap-3 px-0.5 py-1">
      <div><p className="text-xs text-violet-200/45">Good morning, {first} <span aria-hidden="true">👋</span></p><h1 className="mt-0.5 text-xl font-semibold text-white">Here’s what’s happening at {schoolName} today.</h1></div>
      <button className="rounded-lg border border-violet-400/25 bg-violet-500/10 px-3.5 py-2 text-sm font-medium text-violet-100 hover:bg-violet-500/20" onClick={()=>onNavigate("Students")}>＋ Add student</button>
    </header>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="School summary">
      {metrics.map(([label,value,detail,icon,view],index)=><button className={`${panel} group overflow-hidden p-4 text-left transition hover:-translate-y-0.5 hover:border-violet-400/25`} key={label} onClick={()=>onNavigate(view)}><div className="flex items-start justify-between"><div><small className="text-xs font-medium text-white/55">{label}</small><strong className="mt-1 block truncate text-xl font-semibold text-white">{value}</strong></div><span className="grid h-9 w-9 place-items-center rounded-full text-base ring-1" style={{color:accents[index],background:`${accents[index]}15`,boxShadow:`inset 0 0 0 1px ${accents[index]}55`}}>{icon}</span></div><p className="mt-1 text-xs" style={{color:accents[index]}}>↑ <span className="text-white/35">{detail}</span></p><Sparkline index={index}/></button>)}
    </section>

    <section className="grid gap-3 xl:grid-cols-[1.1fr_.9fr]">
      <article className={panel}><div className={panelHeader}><div><h2 className="text-sm font-semibold text-white">Student overview</h2><p className="mt-0.5 text-xs text-white/35">Enrolment across active campuses</p></div><button className="rounded-md border border-white/10 px-2.5 py-1.5 text-xs text-white/50 hover:text-white" onClick={()=>onNavigate("Students")}>View directory</button></div><div className="p-4"><div className="mb-4"><small className="text-xs text-white/35">Total active students</small><strong className="mt-0.5 block text-2xl font-semibold text-white">{activeStudents}</strong></div>{campusCounts.length?<div className="flex h-44 items-end gap-3 border-b border-l border-white/[.07] px-3 pb-0">{campusCounts.map(campus=><div className="flex h-full min-w-0 flex-1 flex-col justify-end gap-2" key={campus.name}><b className="text-center text-xs font-medium text-white/55">{campus.count}</b><div className="mx-auto w-full max-w-12 rounded-t-md" style={{height:`${Math.max(12,campus.count/maxCampus*120)}px`,background:`linear-gradient(180deg,${campus.color},${campus.color}55)`,boxShadow:`0 0 18px ${campus.color}22`}}/><small className="truncate pb-2 text-center text-[11px] text-white/35">{campus.name}</small></div>)}</div>:<div className="grid h-44 place-items-center rounded-lg border border-dashed border-white/10 text-sm text-white/35">Campus data will appear here.</div>}</div></article>

      <article className={panel}><div className={panelHeader}><div><h2 className="text-sm font-semibold text-white">Campus distribution</h2><p className="mt-0.5 text-xs text-white/35">Share of current students</p></div><span className="rounded-md border border-white/10 px-2.5 py-1.5 text-xs text-white/40">Live</span></div><div className="flex flex-col items-center gap-5 p-5 sm:flex-row"><div className="grid h-36 w-36 shrink-0 place-items-center rounded-full p-5" style={{background:campusCounts.length?`conic-gradient(${campusCounts.map((campus,index)=>`${campus.color} ${campusCounts.slice(0,index).reduce((sum,item)=>sum+item.count,0)/total*100}% ${campusCounts.slice(0,index+1).reduce((sum,item)=>sum+item.count,0)/total*100}%`).join(",")})`:"#20243b"}}><span className="grid h-full w-full place-items-center rounded-full bg-[#090d1d] text-center"><span><b className="block text-lg text-white">{activeStudents}</b><small className="text-[11px] text-white/35">Students</small></span></span></div><div className="w-full space-y-3">{campusCounts.map(campus=><div className="grid grid-cols-[8px_1fr_auto_auto] items-center gap-2 text-xs" key={campus.name}><i className="h-2 w-2 rounded-full" style={{background:campus.color}}/><span className="truncate text-white/55">{campus.name}</span><b className="font-medium text-white/75">{campus.count}</b><span className="text-white/30">{Math.round(campus.count/total*100)}%</span></div>)}</div></div></article>
    </section>

    <section className="grid gap-3 lg:grid-cols-[1fr_1fr_1.15fr]">
      <article className={panel}><div className={panelHeader}><h2 className="text-sm font-semibold text-white">Recent activity</h2><button className="text-xs text-violet-300" onClick={()=>onNavigate("Security & Audit")}>View all</button></div><div className="divide-y divide-white/[.06] px-4">{securityData?.logs.slice(0,4).map((log,index)=><div className="flex items-center gap-3 py-3" key={log.id}><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg text-sm" style={{background:`${accents[index%4]}18`,color:accents[index%4]}}>{log.action.includes("student")?"🎓":log.action.includes("campus")?"🏫":log.action.includes("user")?"👤":"🛡️"}</span><div className="min-w-0 flex-1"><b className="block truncate text-xs font-medium capitalize text-white/75">{log.action.replaceAll("."," ")}</b><small className="block truncate text-[11px] text-white/30">{log.actor_name??"System"} · {log.campus_name??"School-wide"}</small></div><time className="text-[10px] text-white/25">{new Date(log.created_at).toLocaleDateString()}</time></div>)}{!securityData?.logs.length&&<p className="py-8 text-center text-xs text-white/30">Activity will appear here.</p>}</div></article>

      <article className={panel}><div className={panelHeader}><h2 className="text-sm font-semibold text-white">Activity trend</h2><span className="text-xs text-white/35">This week</span></div><div className="p-4"><strong className="text-xl font-semibold text-white">{securityData?.logs.length??0}</strong><small className="ml-2 text-xs text-emerald-400">protected actions</small><svg aria-label="Weekly activity trend" className="mt-5 h-36 w-full" viewBox="0 0 320 140" preserveAspectRatio="none"><defs><linearGradient id="activity-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#8b5cf6" stopOpacity=".35"/><stop offset="1" stopColor="#8b5cf6" stopOpacity="0"/></linearGradient></defs>{[28,60,92,124].map(y=><line key={y} x1="0" x2="320" y1={y} y2={y} stroke="white" strokeOpacity=".055"/>)}<path d="M0 120 C35 110 44 77 72 85 S119 97 143 61 S186 86 213 48 S259 64 320 19 L320 140 L0 140Z" fill="url(#activity-fill)"/><path d="M0 120 C35 110 44 77 72 85 S119 97 143 61 S186 86 213 48 S259 64 320 19" fill="none" stroke="#a855f7" strokeWidth="2.5"/></svg></div></article>

      <article className={panel}><div className={panelHeader}><h2 className="text-sm font-semibold text-white">Setup progress</h2><span className="text-xs text-white/35">Phase 8C</span></div><div className="space-y-5 p-4">{[["Secure foundation",100,"#22c55e"],["Student information",92,"#8b5cf6"],["Campus configuration",activeCampuses?84:25,"#d946ef"]].map(([label,value,color])=><div key={String(label)}><div className="mb-2 flex justify-between text-xs"><span className="text-white/55">{label}</span><b className="font-medium text-white/75">{value}%</b></div><div className="h-1.5 overflow-hidden rounded-full bg-white/[.06]"><i className="block h-full rounded-full" style={{width:`${value}%`,background:String(color),boxShadow:`0 0 12px ${color}`}}/></div></div>)}<button className="w-full rounded-lg border border-violet-400/20 bg-violet-500/8 py-2 text-xs font-medium text-violet-200 hover:bg-violet-500/15" onClick={()=>onNavigate("Configuration")}>Open configuration</button></div></article>
    </section>

    <aside className={`${panel} relative overflow-hidden px-5 py-4`}><div className="absolute inset-y-0 right-0 w-64 bg-gradient-to-l from-violet-600/15 to-transparent"/><div className="relative flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold text-white">✦ School insight</h2><p className="mt-1 text-xs text-white/40">Your secure digital campus is ready for the current academic workflow.</p></div><button className="rounded-lg bg-gradient-to-r from-violet-600 to-fuchsia-600 px-3.5 py-2 text-xs font-medium text-white" onClick={()=>onNavigate("Reports")}>View reports</button></div></aside>
  </div>;
}
