"use client";
import { useEffect, useMemo, useState, type FormEvent } from "react";

type Named = { id: string; name: string };
type LearningData = {
  resources: Array<Record<string, string | number | null>>;
  assignments: Array<Record<string, string | number | null>>;
  academicYears: Array<Named & { is_current: number }>;
  classes: Array<Named & { campus_id: string; academic_year_id: string }>;
  sections: Array<Named & { class_id: string; campus_id: string }>;
  subjects: Array<Named & { code: string }>;
  campuses: Array<Named>;
  activeCampusId: string | null;
  canManageResources: boolean;
  canManageAssignments: boolean;
};

const today = () => new Date().toISOString().slice(0, 10);
export default function LearningPanel() {
  const [data, setData] = useState<LearningData | null>(null), [tab, setTab] = useState<"resources" | "assignments">("resources"), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const reload = async () => { const response = await fetch("/api/learning", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Learning workspace unavailable."); setData(body); };
  useEffect(() => { reload().catch((e) => setMessage(e.message)); }, []);
  const defaultYear = data?.academicYears.find((v) => v.is_current)?.id || data?.academicYears[0]?.id || "";
  const activeCampus = data?.activeCampusId || data?.campuses[0]?.id || "";
  const publishedResources = useMemo(() => data?.resources.filter((v) => v.status === "published") ?? [], [data]);
  async function submit(event: FormEvent<HTMLFormElement>, kind: "resource" | "assignment") {
    event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget), body = Object.fromEntries(form.entries());
    try { const response = await fetch("/api/learning", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...body, kind }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); event.currentTarget.reset(); await reload(); setMessage(kind === "resource" ? "Resource saved." : "Assignment saved."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save."); } finally { setBusy(false); }
  }
  async function changeStatus(kind: "resource" | "assignment", id: string, status: string) { setBusy(true); const response = await fetch("/api/learning", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind, id, status }) }); const result = await response.json(); setMessage(response.ok ? "Status updated." : result.error); if (response.ok) await reload(); setBusy(false); }
  async function remove(kind: "resource" | "assignment", id: string) { if (!confirm("Delete this item permanently?")) return; setBusy(true); const response = await fetch(`/api/learning?kind=${kind}&id=${encodeURIComponent(id)}`, { method: "DELETE" }); if (response.ok) await reload(); else setMessage((await response.json()).error); setBusy(false); }
  if (!data) return <section className="learning-shell"><div className="learning-empty">{message || "Loading learning workspace…"}</div></section>;
  const classes = data.classes.filter((v) => !activeCampus || v.campus_id === activeCampus);
  return <section className="learning-shell">
    <div className="phase-heading"><div><span className="eyebrow">PHASE 9 · LEARNING DELIVERY</span><h1>Learning Resources &amp; Assignments</h1><p>Organize curriculum material and publish clearly targeted classwork from one campus-safe workspace.</p></div><span className="phase-badge complete">Learning active</span></div>
    <div className="learning-stats"><article><span>📚</span><strong>{data.resources.length}</strong><small>Resources</small></article><article><span>🚀</span><strong>{publishedResources.length}</strong><small>Published resources</small></article><article><span>📝</span><strong>{data.assignments.length}</strong><small>Assignments</small></article><article><span>⏳</span><strong>{data.assignments.filter(v => v.status === "published" && Number(v.due_at) > Date.now()).length}</strong><small>Open assignments</small></article></div>
    <nav className="learning-tabs"><button className={tab === "resources" ? "active" : ""} onClick={() => setTab("resources")}>📚 Resource library</button><button className={tab === "assignments" ? "active" : ""} onClick={() => setTab("assignments")}>📝 Assignments</button></nav>
    {message && <p className="learning-message">{message}</p>}
    {tab === "resources" ? <div className="learning-grid">
      {data.canManageResources && <form className="learning-card learning-form" onSubmit={(e) => submit(e, "resource")}><header><h2>Add learning resource</h2><p>Share a trusted link or a teacher-authored note.</p></header><label>Title<input name="title" required maxLength={160} /></label><label>Description<textarea name="description" rows={4} /></label><label>Resource link<input name="externalUrl" type="url" placeholder="https://…" /></label><div className="learning-form-grid"><label>Campus<select name="campusId" defaultValue={activeCampus}><option value="">All campuses</option>{data.campuses.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Academic year<select name="academicYearId" defaultValue={defaultYear}><option value="">All years</option>{data.academicYears.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Class<select name="classId"><option value="">All classes</option>{classes.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Subject<select name="subjectId"><option value="">All subjects</option>{data.subjects.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Status<select name="status" defaultValue="published"><option value="published">Published</option><option value="draft">Draft</option></select></label></div><button disabled={busy}>+ Save resource</button></form>}
      <div className="learning-card learning-list"><header><h2>Resource library</h2><p>Published and draft material, newest first.</p></header>{data.resources.length ? data.resources.map(v => <article key={String(v.id)}><div className="learning-item-icon">{v.external_url ? "🔗" : "📄"}</div><div><strong>{String(v.title)}</strong><p>{String(v.description || "No description")}</p><small>{[v.campus_name || "All campuses", v.class_name, v.subject_name].filter(Boolean).join(" · ")}</small></div><span className={`learning-status ${v.status}`}>{String(v.status)}</span>{v.external_url && <a href={String(v.external_url)} target="_blank" rel="noreferrer">Open</a>}{data.canManageResources && <div className="learning-actions"><button disabled={busy} onClick={() => changeStatus("resource", String(v.id), v.status === "published" ? "draft" : "published")}>{v.status === "published" ? "Unpublish" : "Publish"}</button><button className="danger" disabled={busy} onClick={() => remove("resource", String(v.id))}>Delete</button></div>}</article>) : <div className="learning-empty">No resources yet.</div>}</div>
    </div> : <div className="learning-grid">
      {data.canManageAssignments && <form className="learning-card learning-form" onSubmit={(e) => submit(e, "assignment")}><header><h2>Create assignment</h2><p>Target a class or section and attach one published resource.</p></header><label>Title<input name="title" required maxLength={160} /></label><label>Instructions<textarea name="instructions" rows={5} /></label><div className="learning-form-grid"><label>Campus<select name="campusId" required defaultValue={activeCampus}>{data.campuses.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Academic year<select name="academicYearId" required defaultValue={defaultYear}>{data.academicYears.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Class<select name="classId" required defaultValue=""><option value="" disabled>Select class</option>{classes.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Section<select name="sectionId"><option value="">Whole class</option>{data.sections.filter(v => !activeCampus || v.campus_id === activeCampus).map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Subject<select name="subjectId" required defaultValue=""><option value="" disabled>Select subject</option>{data.subjects.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Assigned on<input name="assignedOn" type="date" required defaultValue={today()} /></label><label>Due date &amp; time<input name="dueAt" type="datetime-local" /></label><label>Maximum points<input name="maxPoints" type="number" min="1" max="10000" step="0.5" defaultValue="100" /></label><label>Supporting resource<select name="resourceId"><option value="">None</option>{publishedResources.map(v => <option key={String(v.id)} value={String(v.id)}>{String(v.title)}</option>)}</select></label><label>Status<select name="status" defaultValue="draft"><option value="draft">Draft</option><option value="published">Published</option></select></label></div><button disabled={busy}>+ Save assignment</button></form>}
      <div className="learning-card learning-list"><header><h2>Assignment register</h2><p>Draft, open and completed learning tasks.</p></header>{data.assignments.length ? data.assignments.map(v => <article key={String(v.id)}><div className="learning-item-icon">📝</div><div><strong>{String(v.title)}</strong><p>{String(v.instructions || "No instructions")}</p><small>{[v.class_name, v.section_name || "Whole class", v.subject_name, `${v.max_points} points`].filter(Boolean).join(" · ")}</small><small>{v.due_at ? `Due ${new Date(Number(v.due_at)).toLocaleString()}` : "No due date"}</small></div><span className={`learning-status ${v.status}`}>{String(v.status)}</span>{data.canManageAssignments && <div className="learning-actions"><button disabled={busy} onClick={() => changeStatus("assignment", String(v.id), v.status === "published" ? "closed" : "published")}>{v.status === "published" ? "Close" : "Publish"}</button><button className="danger" disabled={busy} onClick={() => remove("assignment", String(v.id))}>Delete</button></div>}</article>) : <div className="learning-empty">No assignments yet.</div>}</div>
    </div>}
  </section>;
}
