"use client";
import { FormEvent, useEffect, useState } from "react";
type Item={id:string;name:string;message:string;created_at:number};
export default function ParentFeedback(){
 const [items,setItems]=useState<Item[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[id,setId]=useState('');
 async function load(){try{const r=await fetch('/api/parent-feedback',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setItems(d.feedback);setError('')}catch{setError('Unable to load parent feedback. Please try again.')}}
 useEffect(()=>{setId(crypto.randomUUID());void load();const timer=setInterval(()=>{if(!document.hidden)void load()},15000);return()=>clearInterval(timer)},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setBusy(true);setMessage('');try{const r=await fetch('/api/parent-feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,name:data.get('name'),message:data.get('message'),consent:data.get('consent')==='on',website:data.get('website')})});const body=await r.json();if(!r.ok)throw Error(body.error);form.reset();setId(crypto.randomUUID());setMessage('Thank you. Your feedback is now published.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to publish. Please try again.')}finally{setBusy(false)}}
 return <div className="mx-auto mt-10 max-w-5xl text-left"><div className="grid gap-5 md:grid-cols-2">
 <form className="public-live-form" onSubmit={submit}><h3 className="text-xl font-bold">Share your experience</h3><p className="text-sm text-zinc-400">Your name and message will appear publicly. Please leave children’s personal details out of your message.</p><fieldset disabled={busy}><label>Your display name<input name="name" required minLength={2} maxLength={80}/></label><label>Your thoughts<textarea name="message" required minLength={10} maxLength={1000} rows={5}/></label><input name="website" className="hidden" tabIndex={-1} autoComplete="off" aria-hidden="true"/><label className="public-form-consent"><input type="checkbox" name="consent" required/>I agree to publish my name and message on this website.</label><button disabled={!id}>{busy?'Publishing…':'Publish feedback'}</button></fieldset>{message&&<p role="status">{message}</p>}</form>
 <div className="grid max-h-[600px] content-start gap-4 overflow-y-auto" aria-label="Recent parent feedback">{error&&<p role="alert">{error}</p>}{items.length?items.map(item=><blockquote key={item.id} className="rounded-2xl border border-white/15 bg-[#111211] p-6"><p className="whitespace-pre-wrap break-words text-sm leading-relaxed text-zinc-200">{item.message}</p><footer className="mt-4 text-sm"><strong className="text-yellow-400">{item.name}</strong><small className="ml-3 text-zinc-500">{new Date(item.created_at).toLocaleDateString()}</small></footer></blockquote>):!error&&<p className="rounded-2xl border border-white/15 p-6 text-zinc-400">Be the first to share your experience with The Mentor School.</p>}<button type="button" className="text-sm text-yellow-400" onClick={load}>Refresh feedback</button></div></div></div>
}
