"use client";
import { useState } from "react";
import Link from "next/link";

export type PaymentReview={id:string;school_name:string;plan:string;amount_pkr:number;payment_method:string;payment_reference:string;payer_name:string;receipt_name:string;submitted_at:number};
export default function PlatformSubscriptionsPanel({payments}:{payments:PaymentReview[]}){
  const [items,setItems]=useState(payments); const [busy,setBusy]=useState(""); const [message,setMessage]=useState("");
  async function review(paymentId:string,action:"approve"|"reject"){const reviewNote=window.prompt(action==="approve"?"Optional approval note":"Reason for rejection")??"";if(action==="reject"&&!reviewNote.trim())return;setBusy(paymentId);setMessage("");const response=await fetch("/api/platform-admin/subscriptions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({paymentId,action,reviewNote})});const result=await response.json().catch(()=>({error:"Review failed."}));if(response.ok){setItems(v=>v.filter(item=>item.id!==paymentId));setMessage(action==="approve"?"Payment approved and school access activated.":"Payment rejected.");}else setMessage(result.error??"Review failed.");setBusy("");}
  return <main className="min-h-screen bg-slate-950 px-5 py-10 text-white"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.28em] text-fuchsia-300">Platform administration</p><h1 className="mt-2 text-3xl font-black">Subscription approvals</h1></div><Link href="/?portal=dashboard" className="rounded-xl border border-white/20 px-4 py-2 text-sm font-bold">Return to dashboard</Link></header>{message?<p className="mt-6 rounded-xl bg-white/10 p-4">{message}</p>:null}<section className="mt-8 grid gap-5">{items.length?items.map(payment=><article key={payment.id} className="rounded-3xl border border-white/10 bg-white/[.06] p-6"><div className="grid gap-5 lg:grid-cols-[1fr_1fr_auto]"><div><h2 className="text-xl font-black">{payment.school_name}</h2><p className="mt-2 text-sm text-slate-300">{payment.payer_name} · {payment.payment_method} · Ref: {payment.payment_reference}</p><p className="mt-1 text-xs text-slate-500">Submitted {new Date(payment.submitted_at).toLocaleString()}</p></div><div><strong className="text-2xl">Rs. {payment.amount_pkr.toLocaleString()}</strong><p className="capitalize text-slate-300">{payment.plan} plan</p><a href={`/api/platform-admin/subscriptions/receipts/${payment.id}`} target="_blank" className="mt-2 inline-block font-bold text-fuchsia-300 underline">View {payment.receipt_name}</a></div><div className="flex items-center gap-2"><button disabled={busy===payment.id} onClick={()=>review(payment.id,"approve")} className="rounded-xl bg-emerald-500 px-4 py-3 font-black text-emerald-950">Approve</button><button disabled={busy===payment.id} onClick={()=>review(payment.id,"reject")} className="rounded-xl bg-rose-500 px-4 py-3 font-black text-rose-950">Reject</button></div></div></article>):<div className="rounded-3xl border border-white/10 bg-white/[.05] p-10 text-center text-slate-300">No payment receipts are waiting for review.</div>}</section></div></main>;
}
