"use client";
import { useCallback, useEffect, useMemo, useState } from "react";

type CheckRun = { id:string; status:"ready"|"degraded"; application_status:string; database_status:string; storage_status:string; database_latency_ms:number|null; storage_latency_ms:number|null; trigger_type:"manual"|"scheduled"; triggered_by_name:string; created_at:number };
type Incident = { id:string; source:string; severity:"critical"|"high"|"medium"|"low"; status:"open"|"acknowledged"|"resolved"; title:string; description:string|null; resolution_note:string|null; created_by_name:string; acknowledged_by_name:string|null; resolved_by_name:string|null; created_at:number; updated_at:number };
type MonitoringData = { checks:CheckRun[]; incidents:Incident[]; summary:{failedOperations24h:number;lastBackupAt:number|null}; policy:{enabled:number;interval_minutes:number;failure_threshold:number;notify_recovery:number;last_evaluated_at:number|null;last_result:string|null}; canManage:boolean };
const stamp = (value:number|null) => value ? new Date(value).toLocaleString() : "Not available";
const relative = (value:number) => new Intl.RelativeTimeFormat(undefined,{numeric:"auto"}).format(-Math.max(0,Math.round((Date.now()-value)/60000)),"minute");

export default function ProductionReadinessPanel(){
  const [data,setData]=useState<MonitoringData|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/monitoring",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Production monitoring is unavailable.");setData(body);},[]);
  useEffect(()=>{void load().catch(value=>setError(value instanceof Error?value.message:"Production monitoring is unavailable."));const timer=setInterval(()=>{if(document.visibilityState==="visible")void load().catch(()=>undefined)},60000);return()=>clearInterval(timer)},[load]);
  const active=useMemo(()=>data?.incidents.filter(item=>item.status!=="resolved")??[],[data]);
  async function act(body:Record<string,unknown>,success:string){setBusy(true);setError("");setNotice("");try{const response=await fetch("/api/monitoring",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json();if(!response.ok&&response.status!==503)throw new Error(result.error||"The monitoring action failed.");setNotice(response.status===503?"The check found a degraded service and opened an incident.":success);await load();}catch(value){setError(value instanceof Error?value.message:"The monitoring action failed.");}finally{setBusy(false)}}
  async function createIncident(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form).entries());await act({action:"create_incident",...values},"Incident recorded.");form.reset();}
  async function savePolicy(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget);await act({action:"update_policy",enabled:values.get("enabled")==="on",intervalMinutes:Number(values.get("intervalMinutes")),failureThreshold:Number(values.get("failureThreshold")),notifyRecovery:values.get("notifyRecovery")==="on"},"Automation policy updated.")}
  if(!data)return <section className="monitoring-shell"><p className="monitoring-alert error" role="alert">{error||"Loading production monitoring…"}</p></section>;
  const latest=data.checks[0],ready=latest?.status==="ready",backupFresh=Boolean(data.summary.lastBackupAt&&Date.now()-data.summary.lastBackupAt<86400000);
  return <section className="monitoring-shell">
    <header className="monitoring-hero"><div><span>PHASE 16 · OPERATIONAL AUTOMATION & SERVICE ALERTS</span><h1>Operations Command Centre</h1><p>Automated checks, service alerts, recovery posture and incident ownership.</p></div><b className={ready?"ready":"review"}>{latest?(ready?"All systems operational":"Service attention required"):"Run the first check"}</b></header>
    <div className="monitoring-metrics">
      <article><i>◉</i><strong>{latest?.status??"Not checked"}</strong><span>Platform health</span></article>
      <article><i>⚡</i><strong>{data.policy.enabled?`${data.policy.interval_minutes} min`:"Paused"}</strong><span>Automation schedule</span></article>
      <article><i>◆</i><strong>{active.length}</strong><span>Active incidents</span></article>
      <article><i>↻</i><strong className={backupFresh?"good":"warn"}>{backupFresh?"Current":"Attention"}</strong><span>Recovery snapshot</span></article>
    </div>
    {(error||notice)&&<p className={`monitoring-alert ${error?"error":"success"}`} role={error?"alert":"status"}>{error||notice}</p>}
    <div className="monitoring-grid automation-grid">
      <form className="monitoring-card automation-card" onSubmit={savePolicy}><header><div><h2>Automated service checks</h2><p>Runs across the signed-in administrator dashboard while an operator session is active.</p></div><span className={`automation-state ${data.policy.enabled?"on":"off"}`}>{data.policy.enabled?"Enabled":"Paused"}</span></header><div className="automation-controls"><label className="automation-toggle"><input type="checkbox" name="enabled" defaultChecked={Boolean(data.policy.enabled)}/><span><b>Enable automatic checks</b><small>Check D1 and R2 at the selected interval.</small></span></label><div><label>Check interval<select name="intervalMinutes" defaultValue={data.policy.interval_minutes}><option value="5">Every 5 minutes</option><option value="15">Every 15 minutes</option><option value="30">Every 30 minutes</option><option value="60">Every 60 minutes</option></select></label><label>Alert after<select name="failureThreshold" defaultValue={data.policy.failure_threshold}><option value="1">1 failed check</option><option value="2">2 consecutive failures</option><option value="3">3 consecutive failures</option></select></label></div><label className="automation-toggle"><input type="checkbox" name="notifyRecovery" defaultChecked={Boolean(data.policy.notify_recovery)}/><span><b>Send recovery alerts</b><small>Automatically resolve the service incident after recovery.</small></span></label><button disabled={busy}>{busy?"Saving…":"Save automation policy"}</button></div></form>
      <aside className="monitoring-card alert-card"><header><div><h2>Service alerts</h2><p>Alert delivery is limited to authorized operators.</p></div><span>🔔</span></header><div><strong>In-app notifications</strong><p>Principals, school administrators and monitoring auditors receive an alert when the failure threshold is reached.</p><dl><div><dt>Last automation run</dt><dd>{stamp(data.policy.last_evaluated_at)}</dd></div><div><dt>Last result</dt><dd>{data.policy.last_result??"No automated run"}</dd></div><div><dt>Recovery alerts</dt><dd>{data.policy.notify_recovery?"Enabled":"Disabled"}</dd></div></dl></div></aside>
    </div>
    <div className="monitoring-grid">
      <article className="monitoring-card service-card"><header><div><h2>Live services</h2><p>Checks are recorded with the operator and response time.</p></div>{data.canManage&&<button disabled={busy} onClick={()=>act({action:"run_check"},"All production services responded successfully.")}>{busy?"Checking…":"Run service check"}</button>}</header>
        <div className="service-statuses">
          {[['Application',latest?.application_status,'Dashboard and API runtime',null],['Database',latest?.database_status,'School records and permissions',latest?.database_latency_ms],['File storage',latest?.storage_status,'Uploads, receipts and backups',latest?.storage_latency_ms]].map(([name,status,detail,latency])=><div key={String(name)}><i className={status==="ready"?"ready":"down"}>{status==="ready"?"✓":"!"}</i><span><b>{name}</b><small>{detail}</small></span><em>{status??"Not checked"}{typeof latency==="number"?` · ${latency} ms`:""}</em></div>)}
        </div>
        <footer><span>Failed protected operations (24h): <b>{data.summary.failedOperations24h}</b></span><span>Last verified snapshot: <b>{stamp(data.summary.lastBackupAt)}</b></span></footer>
      </article>
      <aside className="monitoring-card runbook-card"><h2>Response runbook</h2><ol><li><b>1. Detect</b><span>Run a service check and confirm the affected component.</span></li><li><b>2. Acknowledge</b><span>Assign operational ownership and protect data-entry activity.</span></li><li><b>3. Recover</b><span>Use the last known-good deployment or verified snapshot.</span></li><li><b>4. Resolve</b><span>Record the action taken and verify service health again.</span></li></ol></aside>
    </div>
    <div className="monitoring-grid incidents-grid">
      <article className="monitoring-card"><header><div><h2>Incident register</h2><p>Open and acknowledged issues remain first until resolved.</p></div><b className="count-badge">{active.length} active</b></header>
        <div className="incident-list">{data.incidents.length?data.incidents.map(item=><article key={item.id} className={`incident-row ${item.status}`}><div><span className={`severity ${item.severity}`}>{item.severity}</span><small>{item.source}</small></div><section><b>{item.title}</b><p>{item.description||"No additional detail."}</p><small>Opened by {item.created_by_name} · {relative(item.created_at)}{item.resolution_note?` · Resolution: ${item.resolution_note}`:""}</small></section><aside><em>{item.status}</em>{data.canManage&&item.status==="open"&&<button disabled={busy} onClick={()=>act({action:"acknowledge_incident",id:item.id},"Incident acknowledged.")}>Acknowledge</button>}{data.canManage&&item.status!=="resolved"&&<button disabled={busy} onClick={()=>{const note=window.prompt("Resolution note");if(note)void act({action:"resolve_incident",id:item.id,note},"Incident resolved.")}}>Resolve</button>}</aside></article>):<div className="monitoring-empty"><span>✓</span><h3>No incidents recorded</h3><p>Degraded service checks automatically create a critical incident.</p></div>}</div>
      </article>
      {data.canManage&&<form className="monitoring-card incident-form" onSubmit={createIncident}><h2>Record an incident</h2><p>Log operational issues that need ownership and follow-up.</p><label>Incident title<input name="title" required maxLength={180}/></label><div><label>Source<select name="source"><option value="manual">Manual report</option><option value="deployment">Deployment</option><option value="database">Database</option><option value="storage">File storage</option><option value="security">Security</option><option value="backup">Backup</option></select></label><label>Severity<select name="severity" defaultValue="medium"><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label></div><label>Description<textarea name="description" rows={5} maxLength={2000}/></label><button disabled={busy}>{busy?"Saving…":"Record incident"}</button></form>}
    </div>
    <article className="monitoring-card"><header><div><h2>Check history</h2><p>The latest 30 manual and automated production checks.</p></div><b className="count-badge">60s refresh</b></header><div className="check-history">{data.checks.length?data.checks.map(item=><div key={item.id}><i className={item.status}>{item.status==="ready"?"✓":"!"}</i><span><b>{item.status==="ready"?"All services ready":"Degraded service detected"}</b><small>{new Date(item.created_at).toLocaleString()} · {item.triggered_by_name} · {item.trigger_type}</small></span><em>DB {item.database_latency_ms??"—"} ms · R2 {item.storage_latency_ms??"—"} ms</em></div>):<p>No checks have been recorded yet.</p>}</div></article>
  </section>
}
