"use client";
import { useCallback, useEffect, useMemo, useState } from "react";

type CheckRun={id:string;status:"ready"|"degraded";application_status:string;database_status:string;storage_status:string;database_latency_ms:number|null;storage_latency_ms:number|null;trigger_type:"manual"|"scheduled";triggered_by_name:string;created_at:number};
type Incident={id:string;source:string;severity:"critical"|"high"|"medium"|"low";status:"open"|"acknowledged"|"resolved";title:string;description:string|null;resolution_note:string|null;created_by_name:string;acknowledged_by_name:string|null;resolved_by_name:string|null;created_at:number;updated_at:number};
type Capacity={databaseLogicalBytes:number|null;storageBytes:number;storageObjectCount:number;databasePercent:number|null;storagePercent:number;database_budget_bytes:number;storage_budget_bytes:number;capacity_warning_percent:number;slow_request_threshold_ms:number;measuredAt:number};
type PerformanceModule={module:string;requests:number;failed:number;slow:number;averageMs:number;p95Ms:number};
type Performance={sampleCount:number;averageMs:number;p50Ms:number;p95Ms:number;failed:number;slow:number;modules:PerformanceModule[];trend:{at:number;requests:number;averageMs:number;failed:number}[]};
type Backup={id:string;status:string;size_bytes:number|null;integrity_status:string;error_message:string|null;created_at:number;completed_at:number|null};
type MonitoringData={checks:CheckRun[];incidents:Incident[];summary:{failedOperations24h:number;lastBackupAt:number|null};policy:{enabled:number;interval_minutes:number;failure_threshold:number;notify_recovery:number;last_evaluated_at:number|null;last_result:string|null};capacity:Capacity;capacityHistory:Record<string,unknown>[];performance:Performance;backups:Backup[];backupIntegrity:{status:"verified"|"mismatch"|"unavailable"|"not_available";checkedAt:number|null;message:string};canManage:boolean};

const stamp=(value:number|null)=>value?new Date(value).toLocaleString():"Not available";
const relative=(value:number)=>{const minutes=Math.max(0,Math.round((Date.now()-value)/60000));if(minutes<60)return `${minutes} min ago`;const hours=Math.round(minutes/60);if(hours<48)return `${hours} hr ago`;return `${Math.round(hours/24)} days ago`};
const bytes=(value:number|null)=>{if(value===null)return "Awaiting backup";if(value<1024)return `${value} B`;const units=["KB","MB","GB","TB"],index=Math.min(units.length-1,Math.floor(Math.log(value)/Math.log(1024))-1);return `${(value/1024**(index+1)).toFixed(index?1:0)} ${units[index]}`};
const percent=(value:number|null)=>value===null?"—":`${Math.min(999,value).toFixed(1)}%`;
const title=(value:string)=>value.split("-").map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(" ");

export default function ProductionReadinessPanel(){
  const[data,setData]=useState<MonitoringData|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[statusFilter,setStatusFilter]=useState(""),[triggerFilter,setTriggerFilter]=useState(""),[days,setDays]=useState("7");
  const load=useCallback(async()=>{const query=new URLSearchParams({days});if(statusFilter)query.set("status",statusFilter);if(triggerFilter)query.set("trigger",triggerFilter);const response=await fetch(`/api/monitoring?${query}`,{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Production monitoring is unavailable.");setData(body)},[days,statusFilter,triggerFilter]);
  useEffect(()=>{void load().catch(value=>setError(value instanceof Error?value.message:"Production monitoring is unavailable."));const timer=setInterval(()=>{if(document.visibilityState==="visible")void load().catch(()=>undefined)},60000);return()=>clearInterval(timer)},[load]);
  const active=useMemo(()=>data?.incidents.filter(item=>item.status!=="resolved")??[],[data]);
  async function act(body:Record<string,unknown>,success:string){setBusy(true);setError("");setNotice("");try{const response=await fetch("/api/monitoring",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json();if(!response.ok&&response.status!==503)throw new Error(result.error||"The monitoring action failed.");setNotice(response.status===503?"The check found a degraded service and opened an incident.":success);await load()}catch(value){setError(value instanceof Error?value.message:"The monitoring action failed.")}finally{setBusy(false)}}
  async function createIncident(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form).entries());await act({action:"create_incident",...values},"Incident recorded.");form.reset()}
  async function savePolicy(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget);await act({action:"update_policy",enabled:values.get("enabled")==="on",intervalMinutes:Number(values.get("intervalMinutes")),failureThreshold:Number(values.get("failureThreshold")),notifyRecovery:values.get("notifyRecovery")==="on"},"Automation policy updated.")}
  async function saveMonitoringSettings(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget);await act({action:"update_monitoring_settings",databaseBudgetMb:Number(values.get("databaseBudgetMb")),storageBudgetGb:Number(values.get("storageBudgetGb")),warningPercent:Number(values.get("warningPercent")),slowRequestMs:Number(values.get("slowRequestMs"))},"Capacity and performance thresholds updated.")}
  if(!data)return <section className="monitoring-shell"><p className="monitoring-alert error" role="alert">{error||"Loading production monitoring…"}</p></section>;
  const latest=data.checks[0],ready=latest?.status==="ready",backupFresh=Boolean(data.summary.lastBackupAt&&Date.now()-data.summary.lastBackupAt<86400000),capacityWarning=(data.capacity.databasePercent??0)>=data.capacity.capacity_warning_percent||data.capacity.storagePercent>=data.capacity.capacity_warning_percent,maxTrend=Math.max(1,...data.performance.trend.map(item=>item.averageMs));
  return <section className="monitoring-shell">
    <header className="monitoring-hero"><div><span>PHASE 15 COMPLETION · PHASE 16 AUTOMATION</span><h1>Operations Command Centre</h1><p>Service health, recovery integrity, capacity budgets and application performance.</p></div><b className={ready&&!capacityWarning?"ready":"review"}>{latest?(ready&&!capacityWarning?"All systems operational":"Operational attention required"):"Run the first check"}</b></header>
    <div className="monitoring-metrics">
      <article><i>◉</i><strong>{latest?.status??"Not checked"}</strong><span>Platform health</span></article>
      <article><i>⚡</i><strong>{data.performance.p95Ms} ms</strong><span>API p95 · 24 hours</span></article>
      <article><i>◆</i><strong>{active.length}</strong><span>Active incidents</span></article>
      <article><i>↻</i><strong className={backupFresh&&data.backupIntegrity.status==="verified"?"good":"warn"}>{data.backupIntegrity.status==="verified"?"Verified":"Attention"}</strong><span>Recovery integrity</span></article>
    </div>
    {(error||notice)&&<p className={`monitoring-alert ${error?"error":"success"}`} role={error?"alert":"status"}>{error||notice}</p>}

    <div className="monitoring-grid capacity-grid">
      <article className="monitoring-card capacity-card"><header><div><h2>Capacity monitoring</h2><p>School-scoped logical D1 data and tracked R2 objects against internal operating budgets.</p></div><span className={`capacity-state ${capacityWarning?"warn":"good"}`}>{capacityWarning?"Warning":"Within budget"}</span></header><div className="capacity-usage">
        <div><div><span><b>D1 logical data</b><small>Measured from the latest tenant recovery snapshot</small></span><strong>{bytes(data.capacity.databaseLogicalBytes)} / {bytes(data.capacity.database_budget_bytes)}</strong></div><span className="capacity-track"><i className={(data.capacity.databasePercent??0)>=data.capacity.capacity_warning_percent?"warn":""} style={{width:`${Math.min(100,data.capacity.databasePercent??0)}%`}}/></span><small>{percent(data.capacity.databasePercent)} used · warning at {data.capacity.capacity_warning_percent}%</small></div>
        <div><div><span><b>R2 file storage</b><small>{data.capacity.storageObjectCount.toLocaleString()} tracked school objects</small></span><strong>{bytes(data.capacity.storageBytes)} / {bytes(data.capacity.storage_budget_bytes)}</strong></div><span className="capacity-track"><i className={data.capacity.storagePercent>=data.capacity.capacity_warning_percent?"warn":""} style={{width:`${Math.min(100,data.capacity.storagePercent)}%`}}/></span><small>{percent(data.capacity.storagePercent)} used · warning at {data.capacity.capacity_warning_percent}%</small></div>
      </div></article>
      <aside className="monitoring-card backup-integrity"><header><div><h2>Backup integrity</h2><p>Latest stored recovery snapshot.</p></div><span className={data.backupIntegrity.status}>{data.backupIntegrity.status.replace("_"," ")}</span></header><div><strong>{backupFresh?"Snapshot is current":"Snapshot is older than 24 hours"}</strong><p>{data.backupIntegrity.message}</p><dl><div><dt>Completed</dt><dd>{stamp(data.summary.lastBackupAt)}</dd></div><div><dt>Stored size</dt><dd>{bytes(data.backups.find(item=>item.status==="completed")?.size_bytes??null)}</dd></div><div><dt>Failed backups</dt><dd>{data.backups.filter(item=>item.status==="failed").length} of latest {data.backups.length}</dd></div></dl></div></aside>
    </div>

    <div className="monitoring-grid performance-grid">
      <article className="monitoring-card performance-card"><header><div><h2>API performance · 24 hours</h2><p>End-to-end dashboard request samples, including failures and slow responses.</p></div><span>{data.performance.sampleCount} samples</span></header><div className="performance-summary"><div><small>Average</small><strong>{data.performance.averageMs} ms</strong></div><div><small>p50</small><strong>{data.performance.p50Ms} ms</strong></div><div><small>p95</small><strong>{data.performance.p95Ms} ms</strong></div><div><small>Failed</small><strong className={data.performance.failed?"warn":"good"}>{data.performance.failed}</strong></div><div><small>Slow</small><strong className={data.performance.slow?"warn":"good"}>{data.performance.slow}</strong></div></div><div className="performance-trend" aria-label="Average API response time in two-hour intervals">{data.performance.trend.map(item=><div key={item.at} title={`${new Date(item.at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}: ${item.averageMs} ms`}><i className={item.failed?"failed":""} style={{height:`${Math.max(4,item.averageMs/maxTrend*100)}%`}}/><small>{new Date(item.at).toLocaleTimeString([], {hour:"numeric"})}</small></div>)}</div></article>
      <aside className="monitoring-card slow-modules"><header><div><h2>Slow modules</h2><p>Ranked by p95 response time.</p></div><span>Threshold {data.capacity.slow_request_threshold_ms} ms</span></header><div>{data.performance.modules.length?data.performance.modules.map(item=><div key={item.module}><span><b>{title(item.module)}</b><small>{item.requests} requests · {item.failed} failed · {item.slow} slow</small></span><strong className={item.p95Ms>=data.capacity.slow_request_threshold_ms?"warn":""}>{item.p95Ms} ms<small>p95</small></strong></div>):<p className="monitoring-list-empty">Performance samples will appear as administrators use dashboard modules.</p>}</div></aside>
    </div>

    {data.canManage&&<form className="monitoring-card threshold-form" onSubmit={saveMonitoringSettings}><header><div><h2>Monitoring thresholds</h2><p>These are school operating budgets, not Cloudflare account limits.</p></div><button disabled={busy}>{busy?"Saving…":"Save thresholds"}</button></header><div><label>D1 budget (MB)<input name="databaseBudgetMb" type="number" min="10" max="10240" defaultValue={Math.round(data.capacity.database_budget_bytes/1024/1024)}/></label><label>R2 budget (GB)<input name="storageBudgetGb" type="number" min="0.1" max="1024" step="0.1" defaultValue={(data.capacity.storage_budget_bytes/1024/1024/1024).toFixed(1)}/></label><label>Capacity warning (%)<input name="warningPercent" type="number" min="50" max="95" defaultValue={data.capacity.capacity_warning_percent}/></label><label>Slow request (ms)<input name="slowRequestMs" type="number" min="200" max="10000" step="100" defaultValue={data.capacity.slow_request_threshold_ms}/></label></div></form>}

    <div className="monitoring-grid automation-grid">
      <form className="monitoring-card automation-card" onSubmit={savePolicy}><header><div><h2>Automated service checks</h2><p>Runs while an authorized administrator dashboard session is active.</p></div><span className={`automation-state ${data.policy.enabled?"on":"off"}`}>{data.policy.enabled?"Enabled":"Paused"}</span></header><div className="automation-controls"><label className="automation-toggle"><input type="checkbox" name="enabled" defaultChecked={Boolean(data.policy.enabled)}/><span><b>Enable automatic checks</b><small>Check D1, R2 and capacity at the selected interval.</small></span></label><div><label>Check interval<select name="intervalMinutes" defaultValue={data.policy.interval_minutes}><option value="5">Every 5 minutes</option><option value="15">Every 15 minutes</option><option value="30">Every 30 minutes</option><option value="60">Every 60 minutes</option></select></label><label>Alert after<select name="failureThreshold" defaultValue={data.policy.failure_threshold}><option value="1">1 failed check</option><option value="2">2 consecutive failures</option><option value="3">3 consecutive failures</option></select></label></div><label className="automation-toggle"><input type="checkbox" name="notifyRecovery" defaultChecked={Boolean(data.policy.notify_recovery)}/><span><b>Send recovery alerts</b><small>Automatically resolve the service incident after recovery.</small></span></label><button disabled={busy}>{busy?"Saving…":"Save automation policy"}</button></div></form>
      <aside className="monitoring-card alert-card"><header><div><h2>Service alerts</h2><p>Alert delivery is limited to authorized operators.</p></div><span>🔔</span></header><div><strong>In-app notifications</strong><p>Principals, school administrators and monitoring auditors receive service and capacity alerts.</p><dl><div><dt>Last automation run</dt><dd>{stamp(data.policy.last_evaluated_at)}</dd></div><div><dt>Last result</dt><dd>{data.policy.last_result??"No automated run"}</dd></div><div><dt>Recovery alerts</dt><dd>{data.policy.notify_recovery?"Enabled":"Disabled"}</dd></div></dl></div></aside>
    </div>

    <div className="monitoring-grid">
      <article className="monitoring-card service-card"><header><div><h2>Live services</h2><p>Checks are recorded with the operator and response time.</p></div>{data.canManage&&<button disabled={busy} onClick={()=>act({action:"run_check"},"All production services responded successfully.")}>{busy?"Checking…":"Run service check"}</button>}</header><div className="service-statuses">{[["Application",latest?.application_status,"Dashboard and API runtime",null],["Database",latest?.database_status,"School records and permissions",latest?.database_latency_ms],["File storage",latest?.storage_status,"Uploads, receipts and backups",latest?.storage_latency_ms]].map(([name,status,detail,latency])=><div key={String(name)}><i className={status==="ready"?"ready":"down"}>{status==="ready"?"✓":"!"}</i><span><b>{name}</b><small>{detail}</small></span><em>{status??"Not checked"}{typeof latency==="number"?` · ${latency} ms`:""}</em></div>)}</div><footer><span>Failed protected operations (24h): <b>{data.summary.failedOperations24h}</b></span><span>Last verified snapshot: <b>{stamp(data.summary.lastBackupAt)}</b></span></footer></article>
      <aside className="monitoring-card runbook-card"><h2>Response runbook</h2><ol><li><b>1. Detect</b><span>Run a service check and confirm the affected component.</span></li><li><b>2. Acknowledge</b><span>Assign operational ownership and protect data-entry activity.</span></li><li><b>3. Recover</b><span>Use the last known-good deployment or verified snapshot.</span></li><li><b>4. Resolve</b><span>Record the action taken and verify service health again.</span></li></ol></aside>
    </div>

    <div className="monitoring-grid incidents-grid">
      <article className="monitoring-card"><header><div><h2>Incident register</h2><p>Open and acknowledged issues remain first until resolved.</p></div><b className="count-badge">{active.length} active</b></header><div className="incident-list">{data.incidents.length?data.incidents.map(item=><article key={item.id} className={`incident-row ${item.status}`}><div><span className={`severity ${item.severity}`}>{item.severity}</span><small>{item.source}</small></div><section><b>{item.title}</b><p>{item.description||"No additional detail."}</p><small>Opened by {item.created_by_name} · {relative(item.created_at)}{item.resolution_note?` · Resolution: ${item.resolution_note}`:""}</small></section><aside><em>{item.status}</em>{data.canManage&&item.status==="open"&&<button disabled={busy} onClick={()=>act({action:"acknowledge_incident",id:item.id},"Incident acknowledged.")}>Acknowledge</button>}{data.canManage&&item.status!=="resolved"&&<button disabled={busy} onClick={()=>{const note=window.prompt("Resolution note");if(note)void act({action:"resolve_incident",id:item.id,note},"Incident resolved.")}}>Resolve</button>}</aside></article>):<div className="monitoring-empty"><span>✓</span><h3>No incidents recorded</h3><p>Service and capacity warnings create incidents automatically.</p></div>}</div></article>
      {data.canManage&&<form className="monitoring-card incident-form" onSubmit={createIncident}><h2>Record an incident</h2><p>Log operational issues that need ownership and follow-up.</p><label>Incident title<input name="title" required maxLength={180}/></label><div><label>Source<select name="source"><option value="manual">Manual report</option><option value="deployment">Deployment</option><option value="database">Database</option><option value="storage">File storage</option><option value="capacity">Capacity</option><option value="performance">Performance</option><option value="security">Security</option><option value="backup">Backup</option></select></label><label>Severity<select name="severity" defaultValue="medium"><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label></div><label>Description<textarea name="description" rows={5} maxLength={2000}/></label><button disabled={busy}>{busy?"Saving…":"Record incident"}</button></form>}
    </div>

    <article className="monitoring-card"><header className="history-header"><div><h2>Monitoring history</h2><p>Filter manual and automated production checks.</p></div><div className="history-filters"><label>Status<select value={statusFilter} onChange={event=>setStatusFilter(event.target.value)}><option value="">All statuses</option><option value="ready">Ready</option><option value="degraded">Degraded</option></select></label><label>Trigger<select value={triggerFilter} onChange={event=>setTriggerFilter(event.target.value)}><option value="">All triggers</option><option value="manual">Manual</option><option value="scheduled">Scheduled</option></select></label><label>Period<select value={days} onChange={event=>setDays(event.target.value)}><option value="1">24 hours</option><option value="7">7 days</option><option value="30">30 days</option></select></label></div></header><div className="check-history">{data.checks.length?data.checks.map(item=><div key={item.id}><i className={item.status}>{item.status==="ready"?"✓":"!"}</i><span><b>{item.status==="ready"?"All services ready":"Degraded service detected"}</b><small>{new Date(item.created_at).toLocaleString()} · {item.triggered_by_name} · {item.trigger_type}</small></span><em>DB {item.database_latency_ms??"—"} ms · R2 {item.storage_latency_ms??"—"} ms</em></div>):<p>No checks match the selected filters.</p>}</div></article>
  </section>
}
