"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Row=Record<string,unknown>&{id:string};
type Data={academicYears:Row[];campuses:Row[];classes:Row[];sections:Row[];rules:Row[];batches:Row[];decisions:Row[];canManage:boolean;canApply:boolean};
const empty:Data={academicYears:[],campuses:[],classes:[],sections:[],rules:[],batches:[],decisions:[],canManage:false,canApply:false};

export default function PromotionPanel(){
  const [data,setData]=useState<Data>(empty),[tab,setTab]=useState<"rules"|"batches">("rules"),[batchId,setBatchId]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  async function load(selected=""){const r=await fetch(`/api/promotions${selected?`?batchId=${encodeURIComponent(selected)}`:""}`,{cache:"no-store"});const j=await r.json();if(r.ok)setData(j);else setMessage(j.error||"Unable to load promotions.");}
  useEffect(()=>{void load();},[]);
  async function send(method:string,payload:Record<string,unknown>){setBusy(true);setMessage("");const r=await fetch("/api/promotions",{method,headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({error:"Request failed."}));setBusy(false);if(!r.ok){setMessage(j.error||"Request failed.");return false;}setMessage(j.applied?`${j.applied} student records were updated successfully.`:"Saved successfully.");return j;}
  async function submit(e:FormEvent<HTMLFormElement>,action:string){e.preventDefault();const result=await send("POST",{action,...Object.fromEntries(new FormData(e.currentTarget))});if(result){if(action==="create_batch"&&typeof result==="object"&&"batchId" in result){setBatchId(String(result.batchId));setTab("batches");await load(String(result.batchId));}else await load(batchId);}}
  async function openBatch(id:string){setBatchId(id);setTab("batches");await load(id);}
  const selectedBatch=data.batches.find(b=>b.id===batchId);
  const rulesByCampus=useMemo(()=>new Map(data.rules.map(rule=>[`${rule.campus_id}:${rule.source_class_id}`,rule])),[data.rules]);
  return <div className="promotion-page foundation-page">
    <div className="phase-heading"><div><span className="eyebrow">PHASE 4D · STUDENT PROGRESSION</span><h1>Promotions and enrollment history</h1><p>Preview, review and apply secure year-end student progression without losing previous enrollment records.</p></div><span className="phase-badge complete">Campus protected</span></div>
    <section className="promotion-stats"><article><span>🧭</span><b>{data.rules.length}</b><small>Promotion rules</small></article><article><span>📝</span><b>{data.batches.filter(b=>b.status==="draft").length}</b><small>Draft batches</small></article><article><span>✅</span><b>{data.batches.filter(b=>b.status==="applied").length}</b><small>Applied batches</small></article><article><span>👥</span><b>{data.batches.reduce((n,b)=>n+Number(b.student_count||0),0)}</b><small>Students reviewed</small></article></section>
    {message&&<p className="promotion-message">{message}</p>}
    <section className="promotion-workspace"><header><nav><button className={tab==="rules"?"active":""} onClick={()=>setTab("rules")}>Promotion rules</button><button className={tab==="batches"?"active":""} onClick={()=>setTab("batches")}>Promotion batches</button></nav></header>
      {tab==="rules"&&<div className="promotion-layout">
        {data.canManage&&<form onSubmit={e=>submit(e,"create_rule")}><h3>Create promotion rule</h3><label>Campus<select name="campusId" required defaultValue=""><option value="" disabled>Select campus</option>{data.campuses.map(c=><option key={c.id} value={c.id}>{String(c.name)}</option>)}</select></label><label>Current class<select name="sourceClassId" required defaultValue=""><option value="" disabled>Select class</option>{data.classes.map(c=><option key={c.id} value={c.id}>{String(c.name)}</option>)}</select></label><label>Default outcome<select name="outcome" defaultValue="promote"><option value="promote">Promote</option><option value="retain">Retain in class</option><option value="graduate">Graduate / alumni</option></select></label><label>Next class<select name="targetClassId" defaultValue=""><option value="">Not required for graduation</option>{data.classes.map(c=><option key={c.id} value={c.id}>{String(c.name)}</option>)}</select></label><label>Default section<select name="targetSectionId" defaultValue=""><option value="">Assign later</option>{data.sections.map(s=><option key={s.id} value={s.id}>{String(s.name)}</option>)}</select></label><button disabled={busy}>Save rule</button></form>}
        <div className="promotion-rule-list">{data.rules.length?data.rules.map(rule=><article key={rule.id}><span>{rule.default_outcome==="graduate"?"🎓":"↗️"}</span><div><small>{String(rule.campus_name)}</small><b>{String(rule.source_class_name)} → {String(rule.target_class_name||"Alumni")}</b><p>{String(rule.default_outcome).replace("_"," ")}{rule.target_section_name?` · ${String(rule.target_section_name)}`:""}</p></div><i>{String(rule.status)}</i></article>):<div className="academic-empty"><span>🧭</span><h3>No promotion rules yet</h3><p>Create one rule for each class before preparing a promotion batch.</p></div>}</div>
      </div>}
      {tab==="batches"&&<div>
        {data.canManage&&<form className="promotion-batch-form" onSubmit={e=>submit(e,"create_batch")}><h3>Prepare a promotion preview</h3><label>Campus<select name="campusId" required defaultValue=""><option value="" disabled>Select campus</option>{data.campuses.map(c=><option key={c.id} value={c.id}>{String(c.name)}</option>)}</select></label><label>Current year<select name="sourceAcademicYearId" required defaultValue=""><option value="" disabled>Select year</option>{data.academicYears.map(y=><option key={y.id} value={y.id}>{String(y.name)}</option>)}</select></label><label>Next year<select name="targetAcademicYearId" required defaultValue=""><option value="" disabled>Select year</option>{data.academicYears.map(y=><option key={y.id} value={y.id}>{String(y.name)}</option>)}</select></label><label>Current class<select name="sourceClassId" required defaultValue=""><option value="" disabled>Select class</option>{data.classes.filter(c=>rulesByCampus.size===0||[...rulesByCampus.values()].some(r=>r.source_class_id===c.id)).map(c=><option key={c.id} value={c.id}>{String(c.name)}</option>)}</select></label><label>Effective date<input name="effectiveOn" type="date" required/></label><button disabled={busy}>Generate preview</button></form>}
        <div className="promotion-batches">{data.batches.map(batch=><article key={batch.id} className={batch.id===batchId?"selected":""}><span>{batch.status==="applied"?"✅":"📝"}</span><div><small>{String(batch.campus_name)} · {String(batch.source_year_name)} → {String(batch.target_year_name)}</small><b>{String(batch.source_class_name)}</b><p>{String(batch.student_count)} students · Effective {String(batch.effective_on)}</p></div><i className={String(batch.status)}>{String(batch.status)}</i><button onClick={()=>openBatch(batch.id)}>Review</button></article>)}</div>
        {selectedBatch&&<section className="promotion-decisions"><header><div><small>PROMOTION PREVIEW</small><h3>{String(selectedBatch.source_class_name)} · {String(selectedBatch.student_count)} students</h3></div>{selectedBatch.status==="draft"&&data.canApply&&<button disabled={busy} onClick={async()=>{if(await send("POST",{action:"apply_batch",batchId})){await load(batchId);}}}>Apply approved batch</button>}</header><div className="promotion-row head"><span>Student</span><span>Outcome</span><span>Target class</span><span>Target section</span><span>Action</span></div>{data.decisions.map(decision=><DecisionRow key={decision.id} decision={decision} data={data} busy={busy} onSave={async payload=>{if(await send("PATCH",payload))await load(batchId);}}/>)}</section>}
      </div>}
    </section>
  </div>;
}

function DecisionRow({decision,data,busy,onSave}:{decision:Row;data:Data;busy:boolean;onSave:(payload:Record<string,unknown>)=>Promise<void>}){
  const [outcome,setOutcome]=useState(String(decision.outcome)),[targetClassId,setTargetClassId]=useState(String(decision.target_class_id||"")),[targetSectionId,setTargetSectionId]=useState(String(decision.target_section_id||""));
  const availableClasses=data.classes.filter(c=>!c.campus_id||c.campus_id===decision.target_campus_id),availableSections=data.sections.filter(s=>s.class_id===targetClassId);
  return <div className="promotion-row"><span><b>{String(decision.first_name)} {String(decision.last_name||"")}</b><small>{String(decision.admission_number)} · {String(decision.current_class_name||"")}</small></span><span><select value={outcome} disabled={decision.status!=="draft"} onChange={e=>setOutcome(e.target.value)}><option value="promote">Promote</option><option value="retain">Retain</option><option value="graduate">Graduate</option><option value="withdraw">Withdraw</option></select></span><span><select value={targetClassId} disabled={decision.status!=="draft"||["graduate","withdraw"].includes(outcome)} onChange={e=>{setTargetClassId(e.target.value);setTargetSectionId("");}}><option value="">Select class</option>{availableClasses.map(c=><option key={c.id} value={c.id}>{String(c.name)}</option>)}</select></span><span><select value={targetSectionId} disabled={decision.status!=="draft"||["graduate","withdraw"].includes(outcome)} onChange={e=>setTargetSectionId(e.target.value)}><option value="">Assign later</option>{availableSections.map(s=><option key={s.id} value={s.id}>{String(s.name)}</option>)}</select></span><span>{decision.status==="draft"?<button disabled={busy} onClick={()=>onSave({decisionId:decision.id,outcome,targetClassId,targetSectionId})}>Save</button>:<i className="applied">Applied</i>}</span></div>;
}
