"use client";
import { useState } from "react";
import type { OrganizationChoice } from "../lib/authorization";
import AuthVisualShell from "./AuthVisualShell";

export default function SchoolSelectionPanel({schools,userName}:{schools:OrganizationChoice[];userName:string}){
  const [busy,setBusy]=useState("");const [error,setError]=useState("");
  async function choose(organizationId:string){setBusy(organizationId);setError("");const response=await fetch("/api/session/context",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId})});const result=await response.json().catch(()=>({error:"School selection failed."}));if(!response.ok){setError(result.error);setBusy("");return;}window.location.reload();}
  return <AuthVisualShell title="Welcome" subtitle="Choose the school you want to manage." description="Your verified account belongs to more than one school workspace. Your permissions remain separate in every school."><div className="mb-7"><span className="text-xs font-black uppercase tracking-[.22em] text-fuchsia-200/75">Secure school context</span><h2 className="mt-3 text-3xl font-black tracking-tight">Select your school</h2><p className="mt-2 text-sm leading-6 text-violet-100/65">{userName}, choose the workspace you want to open.</p></div><div className="grid gap-3">{schools.map(school=><button className="grid grid-cols-[44px_1fr] items-center gap-x-3 rounded-2xl border border-white/12 bg-white/[.07] p-4 text-left transition hover:border-fuchsia-300/35 hover:bg-white/10 disabled:cursor-wait disabled:opacity-60" key={school.organizationId} disabled={!!busy} onClick={()=>choose(school.organizationId)}><span className="row-span-2 grid h-11 w-11 place-items-center rounded-xl bg-violet-400/15 text-xl" aria-hidden="true">🏫</span><b className="text-sm text-white">{school.schoolName}</b><small className="text-sm text-violet-100/55">{busy===school.organizationId?"Opening…":"Open secure workspace"}</small></button>)}</div>{error&&<p className="mt-4 rounded-xl border border-rose-300/20 bg-rose-400/10 p-3 text-sm text-rose-100" role="alert">{error}</p>}</AuthVisualShell>;
}
