"use client";
import { FormEvent, useState } from "react";
import { cn, moduleSurface } from "./ui/TailwindPrimitives";

export type SecurityData={
  logs:{id:string;action:string;entity_type:string;entity_id:string|null;outcome:string;created_at:number;actor_name:string|null;campus_name:string|null}[];
  campuses:{id:string;name:string}[];
  backups:{id:string;status:string;size_bytes:number|null;created_at:number;completed_at:number|null;actor_name:string|null}[];
  summary:{events24h:number;failed24h:number;sensitive24h:number;lastBackupAt:number|null};
};

const date=(value:number|null)=>value?new Date(value).toLocaleString():"Not yet";
export default function SecurityPanel({data}:{data:SecurityData}){
  const [tab,setTab]=useState<"audit"|"security"|"backup">("audit");
  const [logs,setLogs]=useState(data.logs),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function filter(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const query=new URLSearchParams(new FormData(event.currentTarget) as never);const response=await fetch(`/api/security/audit?${query}`);const result=await response.json();setBusy(false);if(response.ok)setLogs(result.logs);else setMessage(result.error??"Could not load audit history.");}
  async function backup(){setBusy(true);setMessage("");const response=await fetch("/api/security/backups",{method:"POST"});const result=await response.json().catch(()=>({}));if(!response.ok){setMessage(result.error??"Backup could not be created.");setBusy(false);return;}window.location.reload();}
  return <div className={cn("security-page",moduleSurface)}>
    <div className="access-heading"><div><span className="eyebrow">PHASE 0E · PROTECTION</span><h1>Audit, Security & Recovery</h1><p>Organization-isolated activity monitoring, defensive controls and recoverable snapshots.</p></div><span className="phase-badge complete">0E Active</span></div>
    <div className="security-stats"><article><span>🧾</span><strong>{data.summary.events24h}</strong><small>events in 24 hours</small></article><article><span>🛡️</span><strong>{data.summary.failed24h}</strong><small>failed operations</small></article><article><span>🔐</span><strong>{data.summary.sensitive24h}</strong><small>sensitive actions</small></article><article><span>💾</span><strong>{date(data.summary.lastBackupAt)}</strong><small>last backup</small></article></div>
    <div className="config-tabs"><button className={tab==="audit"?"active":""} onClick={()=>setTab("audit")}>🧾 Audit history</button><button className={tab==="security"?"active":""} onClick={()=>setTab("security")}>🛡️ Security controls</button><button className={tab==="backup"?"active":""} onClick={()=>setTab("backup")}>💾 Backup & recovery</button></div>
    {message&&<p className="access-message">{message}</p>}
    {tab==="audit"&&<section className="security-card"><form className="audit-filters" onSubmit={filter}><label>Action<input name="action" placeholder="e.g. campus.update"/></label><label>Campus<select name="campusId"><option value="">All campuses</option>{data.campuses.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Outcome<select name="outcome"><option value="">All outcomes</option><option>success</option><option>denied</option><option>failed</option></select></label><button disabled={busy}>{busy?"Loading…":"Apply filters"}</button></form><div className="audit-table"><div className="audit-row audit-head"><span>Time</span><span>User / Campus</span><span>Action</span><span>Record</span><span>Outcome</span></div>{logs.map(l=><div className="audit-row" key={l.id}><span>{date(l.created_at)}</span><span><strong>{l.actor_name??"System"}</strong><small>{l.campus_name??"All campuses"}</small></span><span>{l.action}</span><span>{l.entity_type}{l.entity_id?<small>{l.entity_id.slice(0,12)}</small>:null}</span><b className={`audit-outcome ${l.outcome}`}>{l.outcome}</b></div>)}</div></section>}
    {tab==="security"&&<div className="security-grid"><article><span>🔒</span><div><strong>Server-side authorization</strong><p>Protected routes resolve organization membership and permissions before every operation.</p></div><b>Active</b></article><article><span>🏢</span><div><strong>Tenant & campus isolation</strong><p>Queries validate organization ownership; campus records cannot cross school boundaries.</p></div><b>Active</b></article><article><span>⏱️</span><div><strong>Rate limiting</strong><p>Sensitive operations are restricted per user, organization and time window.</p></div><b>Active</b></article><article><span>📦</span><div><strong>Protected R2 files</strong><p>Files use tenant-scoped keys and require permission-checked download routes.</p></div><b>Active</b></article><article><span>🧪</span><div><strong>Input & request validation</strong><p>Same-origin enforcement, content-type checks, size limits and prepared SQL are enabled.</p></div><b>Active</b></article><article><span>🧹</span><div><strong>Retention foundation</strong><p>Audit history is immutable in the interface and backup manifests include creation metadata.</p></div><b>Ready</b></article></div>}
    {tab==="backup"&&<div className="config-layout"><section className="security-card backup-list"><div className="card-title"><h2>Backup history</h2><p>Encrypted-platform storage snapshots are isolated by organization.</p></div>{data.backups.length?data.backups.map(b=><article key={b.id}><span>💾</span><div><strong>{date(b.created_at)}</strong><small>Requested by {b.actor_name??"System"} · {b.size_bytes?`${Math.ceil(b.size_bytes/1024)} KB`:"—"}</small></div><b className={`audit-outcome ${b.status}`}>{b.status}</b></article>):<p className="empty-state">No backups have been created yet.</p>}</section><section className="security-card backup-action"><span>☁️</span><h2>Create recovery snapshot</h2><p>Captures school configuration, campuses, users, roles, academic years, assets metadata and audit history. File bytes remain protected in R2.</p><button disabled={busy} onClick={backup}>{busy?"Creating…":"Create backup now"}</button><small>Restore remains a supervised administrator operation during the foundation phase.</small></section></div>}
  </div>;
}
