"use client";
import { useEffect, useMemo, useState } from "react";

type Row=Record<string,unknown>&{id?:string};
type Data={academicYears:Row[];campuses:Row[];classes:Row[];sections:Row[];recent:Row[];session:Row|null;roster:Row[];history:Row[];canManage:boolean;canCorrect:boolean};
const empty:Data={academicYears:[],campuses:[],classes:[],sections:[],recent:[],session:null,roster:[],history:[],canManage:false,canCorrect:false};
const today=new Date().toISOString().slice(0,10);
const options=["present","absent","late","leave","half_day"] as const;

export default function StudentAttendancePanel(){
  const [view,setView]=useState<"register"|"reports">("register"),[data,setData]=useState<Data>(empty),[filters,setFilters]=useState({date:today,academicYearId:"",campusId:"",classId:"",sectionId:""}),[rows,setRows]=useState<Row[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[correctionReason,setCorrectionReason]=useState("");
  async function load(next=filters){setBusy(true);setMessage("");const query=new URLSearchParams(Object.entries(next).filter(([,value])=>value));const response=await fetch(`/api/student-attendance?${query}`,{cache:"no-store"}),json=await response.json();setBusy(false);if(!response.ok){setMessage(json.error||"Unable to load attendance.");return;}setData(json);setRows(json.roster||[]);if(!next.academicYearId){const year=json.academicYears.find((item:Row)=>item.is_current)||json.academicYears[0],campus=json.campuses[0];setFilters(current=>({...current,academicYearId:String(year?.id||""),campusId:String(campus?.id||"")}));}}
  useEffect(()=>{void load();},[]);
  function updateFilter(name:string,value:string){setFilters(current=>({...current,[name]:value,...(name==="campusId"?{classId:"",sectionId:""}:{}),...(name==="classId"?{sectionId:""}:{})}));}
  const visibleClasses=data.classes.filter(item=>!item.campus_id||item.campus_id===filters.campusId),visibleSections=data.sections.filter(item=>item.class_id===filters.classId),counts=useMemo(()=>Object.fromEntries(options.map(status=>[status,rows.filter(row=>row.attendance_status===status).length])),[rows]);
  function setAll(status:string){setRows(current=>current.map(row=>({...row,attendance_status:status})))}
  function updateRow(studentId:unknown,field:string,value:string){setRows(current=>current.map(row=>row.student_id===studentId?{...row,[field]:value}:row));}
  async function save(){setBusy(true);setMessage("");const response=await fetch("/api/student-attendance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...filters,correctionReason,records:rows.map(row=>({studentId:row.student_id,enrollmentId:row.enrollment_id,status:row.attendance_status,remarks:row.remarks}))})}),json=await response.json();setBusy(false);if(!response.ok){setMessage(json.error||"Attendance could not be saved.");return;}setMessage("Attendance register saved successfully.");setCorrectionReason("");await load();}
  return <div className="student-attendance-page foundation-page">
    <div className="phase-heading"><div><span className="eyebrow">PHASE 5B · ATTENDANCE INSIGHTS</span><h1>Student attendance</h1><p>Manage daily registers, monthly performance, parent visibility, corrections and absence alerts.</p></div><span className="phase-badge complete">School & campus protected</span></div>
    <nav className="attendance-view-tabs"><button className={view==="register"?"active":""} onClick={()=>setView("register")}>Daily register</button><button className={view==="reports"?"active":""} onClick={()=>setView("reports")}>Reports & corrections</button></nav>
    {view==="register"&&<>
    <section className="student-attendance-stats">{options.map(status=><article key={status}><span>{status==="present"?"✅":status==="absent"?"❌":status==="late"?"⏰":status==="leave"?"📝":"◐"}</span><b>{Number(counts[status]||0)}</b><small>{status.replace("_"," ")}</small></article>)}</section>
    {message&&<p className="attendance-message">{message}</p>}
    <section className="attendance-workspace">
      <div className="attendance-filters"><label>Date<input type="date" value={filters.date} onChange={event=>updateFilter("date",event.target.value)}/></label><label>Academic year<select value={filters.academicYearId} onChange={event=>updateFilter("academicYearId",event.target.value)}><option value="">Select year</option>{data.academicYears.map(item=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label><label>Campus<select value={filters.campusId} onChange={event=>updateFilter("campusId",event.target.value)}><option value="">Select campus</option>{data.campuses.map(item=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label><label>Class<select value={filters.classId} onChange={event=>updateFilter("classId",event.target.value)}><option value="">Select class</option>{visibleClasses.map(item=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label><label>Section<select value={filters.sectionId} onChange={event=>updateFilter("sectionId",event.target.value)}><option value="">All / no section</option>{visibleSections.map(item=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label><button disabled={busy||!filters.classId} onClick={()=>load()}>Open register</button></div>
      {rows.length?<><div className="attendance-toolbar"><div><b>{rows.length} enrolled students</b><small>{data.session?`Existing ${String(data.session.status)} register`:`New register for ${filters.date}`}</small></div><div><button onClick={()=>setAll("present")}>✓ Mark all present</button><button onClick={()=>setAll("absent")}>Mark all absent</button></div></div><div className="attendance-table"><div className="attendance-row head"><span>Student</span><span>Roll no.</span><span>Status</span><span>Remarks</span></div>{rows.map(row=><div className="attendance-row" key={String(row.student_id)}><span><b>{String(row.first_name)} {String(row.last_name||"")}</b><small>{String(row.admission_number)}</small></span><span>{String(row.roll_number||"—")}</span><span><select className={String(row.attendance_status)} value={String(row.attendance_status)} onChange={event=>updateRow(row.student_id,"attendance_status",event.target.value)}>{options.map(status=><option key={status} value={status}>{status.replace("_"," ")}</option>)}</select></span><span><input value={String(row.remarks||"")} placeholder="Optional note" onChange={event=>updateRow(row.student_id,"remarks",event.target.value)}/></span></div>)}</div><footer className="attendance-submit">{data.session&&<label>Correction reason<input value={correctionReason} onChange={event=>setCorrectionReason(event.target.value)} placeholder="Required when changing submitted attendance"/></label>}<button disabled={busy||!data.canManage} onClick={save}>{data.session?"Save correction":"Submit attendance"}</button></footer></>:<div className="attendance-empty"><span>🗓️</span><h3>Open a daily register</h3><p>Select the academic year, campus, class, section and date to load enrolled students.</p></div>}
    </section>
    <section className="attendance-recent"><header><div><span>📊</span><div><h2>Recent attendance registers</h2><p>Daily totals remain available for summaries and reporting.</p></div></div></header><div>{data.recent.length?data.recent.map(item=><article key={String(item.id)}><span>🗓️</span><div><b>{String(item.class_name)}{item.section_name?` · ${String(item.section_name)}`:""}</b><small>{String(item.campus_name)} · {String(item.attendance_date)} · Marked by {String(item.marked_by_name)}</small></div><div className="attendance-mini"><i>{String(item.present_count)} present</i><i>{String(item.absent_count)} absent</i><i>{String(item.late_count)} late</i></div></article>):<div className="attendance-empty compact">No attendance registers have been submitted yet.</div>}</div></section></>}
    {view==="reports"&&<AttendanceReportsPanel/>}
  </div>;
}

type ReportData={from:string;to:string;campuses:Row[];classes:Row[];sections:Row[];daily:Row[];students:Row[];records:Row[];correctionRequests:Row[];alerts:Row[];linkedOnly:boolean;canRequest:boolean;canApprove:boolean;minimumAttendance:number};
function AttendanceReportsPanel(){
  const month=today.slice(0,7),[filters,setFilters]=useState({from:`${month}-01`,to:today,campusId:"",classId:"",sectionId:""}),[data,setData]=useState<ReportData|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[requesting,setRequesting]=useState<Row|null>(null),[requestedStatus,setRequestedStatus]=useState("present"),[reason,setReason]=useState("");
  async function load(next=filters){setBusy(true);const query=new URLSearchParams(Object.entries(next).filter(([,value])=>value)),response=await fetch(`/api/student-attendance/reports?${query}`,{cache:"no-store"}),json=await response.json();setBusy(false);if(!response.ok){setMessage(json.error||"Unable to load reports.");return;}setData(json);setMessage("");}
  useEffect(()=>{void load();},[]);
  async function action(payload:Record<string,unknown>){setBusy(true);const response=await fetch("/api/student-attendance/reports",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),json=await response.json();setBusy(false);if(!response.ok){setMessage(json.error||"Request failed.");return;}setMessage("Attendance workflow updated successfully.");setRequesting(null);setReason("");await load();}
  if(!data)return <div className="attendance-empty"><span>📊</span><h3>{busy?"Preparing attendance reports…":"Reports are unavailable"}</h3><p>{message}</p></div>;
  const atRisk=data.students.filter(item=>Number(item.attendance_percentage)<data.minimumAttendance),total=data.daily.reduce((sum,item)=>sum+Number(item.total||0),0),present=data.daily.reduce((sum,item)=>sum+Number(item.present||0),0),rate=total?Math.round(present/total*1000)/10:0,visibleClasses=data.classes.filter(item=>!filters.campusId||!item.campus_id||item.campus_id===filters.campusId),visibleSections=data.sections.filter(item=>item.class_id===filters.classId);
  return <div className="attendance-report-space">
    <div className="attendance-report-filters"><label>From<input type="date" value={filters.from} onChange={event=>setFilters({...filters,from:event.target.value})}/></label><label>To<input type="date" value={filters.to} onChange={event=>setFilters({...filters,to:event.target.value})}/></label><label>Campus<select value={filters.campusId} onChange={event=>setFilters({...filters,campusId:event.target.value,classId:"",sectionId:""})}><option value="">All permitted</option>{data.campuses.map(item=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label><label>Class<select value={filters.classId} onChange={event=>setFilters({...filters,classId:event.target.value,sectionId:""})}><option value="">All classes</option>{visibleClasses.map(item=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label><label>Section<select value={filters.sectionId} onChange={event=>setFilters({...filters,sectionId:event.target.value})}><option value="">All sections</option>{visibleSections.map(item=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label><button disabled={busy} onClick={()=>load()}>Apply filters</button><button onClick={()=>window.print()}>🖨 Print</button></div>
    {message&&<p className="attendance-message">{message}</p>}
    <section className="report-kpis"><article><span>📈</span><b>{rate}%</b><small>Present rate</small></article><article><span>👥</span><b>{data.students.length}</b><small>Students</small></article><article><span>⚠️</span><b>{atRisk.length}</b><small>Below 85%</small></article><article><span>🔔</span><b>{data.alerts.filter(item=>item.status==="queued").length}</b><small>Queued alerts</small></article></section>
    <section className="attendance-report-card"><header><div><h2>Student attendance summary</h2><p>{data.linkedOnly?"Showing only students linked to your account.":"Present, absent, late, leave and half-day performance."}</p></div></header><div className="report-row head"><span>Student</span><span>Class</span><span>Present</span><span>Absent / Late</span><span>Attendance</span></div>{data.students.map(item=><div className="report-row" key={String(item.id)}><span><b>{String(item.first_name)} {String(item.last_name||"")}</b><small>{String(item.admission_number)}</small></span><span>{String(item.class_name||"—")} {item.section_name?`· ${String(item.section_name)}`:""}</span><span>{String(item.present)} / {String(item.total)}</span><span>{String(item.absent)} / {String(item.late)}</span><span><i className={Number(item.attendance_percentage)<data.minimumAttendance?"risk":"good"}>{String(item.attendance_percentage)}%</i></span></div>)}</section>
    {data.canRequest&&<section className="attendance-report-card"><header><div><h2>Attendance details</h2><p>Select a record when a correction request is required.</p></div></header><div className="attendance-detail-grid">{data.records.slice(0,40).map(item=><article key={String(item.id)}><div><b>{String(item.first_name)} {String(item.last_name||"")}</b><small>{String(item.attendance_date)} · {String(item.status).replace("_"," ")}</small></div><button onClick={()=>{setRequesting(item);setRequestedStatus(String(item.status));}}>Request correction</button></article>)}</div></section>}
    {data.canApprove&&<section className="attendance-report-card"><header><div><h2>Correction requests</h2><p>Approve or reject requested changes with a permanent audit record.</p></div></header><div className="correction-list">{data.correctionRequests.map(item=><article key={String(item.id)}><div><b>{String(item.first_name)} {String(item.last_name||"")}</b><small>{String(item.attendance_date)} · {String(item.current_status)} → {String(item.requested_status)}</small><p>{String(item.reason)}</p></div>{item.status==="pending"?<div><button onClick={()=>action({action:"review_correction",requestId:item.id,decision:"approve"})}>Approve</button><button onClick={()=>action({action:"review_correction",requestId:item.id,decision:"reject"})}>Reject</button></div>:<i>{String(item.status)}</i>}</article>)}</div></section>}
    {requesting&&<div className="attendance-request-modal"><form onSubmit={event=>{event.preventDefault();void action({action:"request_correction",attendanceRecordId:requesting.id,requestedStatus,reason});}}><button type="button" onClick={()=>setRequesting(null)}>×</button><span>ATTENDANCE CORRECTION</span><h2>{String(requesting.first_name)} {String(requesting.last_name||"")}</h2><p>{String(requesting.attendance_date)} · Current status: {String(requesting.status)}</p><label>Requested status<select value={requestedStatus} onChange={event=>setRequestedStatus(event.target.value)}>{options.map(item=><option key={item} value={item}>{item.replace("_"," ")}</option>)}</select></label><label>Reason<textarea required minLength={5} value={reason} onChange={event=>setReason(event.target.value)} placeholder="Explain why this record should be corrected"/></label><button disabled={busy}>Submit request</button></form></div>}
  </div>;
}
