"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import type { SubscriptionRecord } from "../lib/subscriptions";
import AuthVisualShell from "./AuthVisualShell";

export default function SubscriptionPanel({ schoolName, subscription, pendingPayment, now }: { schoolName:string; subscription:SubscriptionRecord; pendingPayment:boolean; now:number }) {
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const entitled=subscription.status==="active"||(subscription.status==="trialing"&&!!subscription.trial_ends_at&&subscription.trial_ends_at>now);
  const days=subscription.trial_ends_at?Math.max(0,Math.ceil((subscription.trial_ends_at-now)/86400000)):0;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const response=await fetch("/api/subscription/receipt",{method:"POST",body:new FormData(event.currentTarget)});const result=await response.json().catch(()=>({error:"Receipt could not be submitted."}));setMessage(response.ok?"Receipt submitted. HAZA-SMS administration will review it before activating access.":result.error??"Receipt could not be submitted.");setBusy(false);if(response.ok) window.location.reload();}
  const fieldClass="min-h-12 rounded-xl border border-white/15 bg-white/10 p-3 text-white outline-none focus:border-fuchsia-300/60 focus:ring-4 focus:ring-fuchsia-400/10";
  return <AuthVisualShell wide title="School subscription" subtitle="Secure access for your complete school workspace." description="Choose your plan, submit payment proof and track approval without leaving HAZA-SMS.">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><span className="text-xs font-black uppercase tracking-[.22em] text-fuchsia-200/75">HAZA-SMS subscription</span><h2 className="mt-3 text-3xl font-black">{schoolName}</h2></div><div className="flex gap-3">{entitled?<Link href="/?portal=dashboard" className="rounded-xl bg-gradient-to-r from-violet-500 to-fuchsia-600 px-4 py-2 text-sm font-black text-white">Open dashboard</Link>:null}<a href="/signout-with-chatgpt?return_to=/" className="rounded-xl border border-white/20 px-4 py-2 text-sm font-bold text-violet-100">Sign out</a></div></div>
    <article className="mt-6 rounded-2xl border border-white/12 bg-white/[.07] p-5"><p className="text-sm text-violet-200">Current status</p><h3 className="mt-1 text-2xl font-black capitalize">{subscription.status.replaceAll("_"," ")}</h3><p className="mt-3 text-sm leading-6 text-violet-100/70">{subscription.status==="trialing"?`${days} demo day${days===1?"":"s"} remaining.`:subscription.status==="active"?"Your school dashboard is active.":subscription.status==="pending_review"?"Your payment receipt is awaiting review.":"Payment approval is required before this school can enter the dashboard."}</p></article>
    <div className="mt-7"><h3 className="text-2xl font-black">Submit payment receipt</h3><p className="mt-2 text-sm leading-6 text-violet-100/70">Pay by bank transfer, JazzCash or Easypaisa using the account details supplied by HAZA-SMS administration, then upload proof here.</p>{pendingPayment?<div className="mt-5 rounded-2xl border border-amber-300/25 bg-amber-300/10 p-4 text-sm text-amber-100">A receipt is already pending review. You do not need to submit it again.</div>:<form onSubmit={submit} className="mt-5 grid gap-4"><label className="grid gap-2 text-sm font-bold text-white/85">Plan<select name="plan" defaultValue={subscription.plan==="yearly"?"yearly":"monthly"} className={fieldClass}><option className="bg-purple-950" value="monthly">Monthly — Rs. 5,000</option><option className="bg-purple-950" value="yearly">Yearly — Rs. 50,000</option></select></label><label className="grid gap-2 text-sm font-bold text-white/85">Payment method<select name="paymentMethod" className={fieldClass}><option className="bg-purple-950" value="bank">Bank transfer</option><option className="bg-purple-950" value="jazzcash">JazzCash</option><option className="bg-purple-950" value="easypaisa">Easypaisa</option></select></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold text-white/85">Payer name<input name="payerName" required maxLength={100} className={fieldClass} /></label><label className="grid gap-2 text-sm font-bold text-white/85">Transaction reference<input name="paymentReference" required maxLength={120} className={fieldClass} /></label></div><label className="grid gap-2 text-sm font-bold text-white/85">Receipt image or PDF<input name="receipt" type="file" required accept="image/jpeg,image/png,image/webp,application/pdf" className="rounded-xl border border-dashed border-white/25 bg-white/5 p-4 text-sm" /><small className="font-normal text-violet-200/65">JPEG, PNG, WebP or PDF up to 8 MB.</small></label>{message?<p role="status" className="rounded-xl border border-white/10 bg-white/10 p-3 text-sm">{message}</p>:null}<button disabled={busy} className="min-h-14 rounded-2xl bg-gradient-to-r from-violet-500 via-fuchsia-500 to-purple-700 font-black text-white shadow-lg shadow-fuchsia-950/40 disabled:opacity-60">{busy?"Uploading receipt…":"Submit receipt for approval"}</button></form>}</div>
  </AuthVisualShell>;
}
