"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import type { SubscriptionRecord } from "../lib/subscriptions";

export default function SubscriptionPanel({ schoolName, subscription, pendingPayment, now }: { schoolName:string; subscription:SubscriptionRecord; pendingPayment:boolean; now:number }) {
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const entitled=subscription.status==="active"||(subscription.status==="trialing"&&!!subscription.trial_ends_at&&subscription.trial_ends_at>now);
  const days=subscription.trial_ends_at?Math.max(0,Math.ceil((subscription.trial_ends_at-now)/86400000)):0;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const response=await fetch("/api/subscription/receipt",{method:"POST",body:new FormData(event.currentTarget)});const result=await response.json().catch(()=>({error:"Receipt could not be submitted."}));setMessage(response.ok?"Receipt submitted. HAZA-SMS administration will review it before activating access.":result.error??"Receipt could not be submitted.");setBusy(false);if(response.ok) window.location.reload();}
  return <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#6b21a8,#270646_42%,#10051f)] px-5 py-10 text-white">
    <div className="mx-auto max-w-5xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.28em] text-fuchsia-200">HAZA-SMS subscription</p><h1 className="mt-2 text-3xl font-black">{schoolName}</h1></div><div className="flex gap-3">{entitled?<Link href="/?portal=dashboard" className="rounded-xl bg-white px-4 py-2 text-sm font-black text-purple-950">Open dashboard</Link>:null}<a href="/signout-with-chatgpt?return_to=/" className="rounded-xl border border-white/20 px-4 py-2 text-sm font-bold">Sign out</a></div></header>
      <section className="mt-10 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><article className="rounded-3xl border border-white/15 bg-white/[.08] p-7"><p className="text-sm text-violet-200">Current status</p><h2 className="mt-2 text-3xl font-black capitalize">{subscription.status.replaceAll("_"," ")}</h2><p className="mt-5 leading-7 text-violet-100/70">{subscription.status==="trialing"?`${days} demo day${days===1?"":"s"} remaining.`:subscription.status==="active"?"Your school dashboard is active.":subscription.status==="pending_review"?"Your payment receipt is awaiting review.":"Payment approval is required before this school can enter the dashboard."}</p><div className="mt-6 rounded-2xl bg-black/15 p-4 text-sm leading-6 text-violet-100/70"><strong className="block text-white">Access protection</strong>Inactive and expired schools are blocked server-side from protected dashboards and APIs.</div></article>
      <article className="rounded-3xl border border-white/15 bg-[#260b45]/80 p-7"><h2 className="text-2xl font-black">Submit payment receipt</h2><p className="mt-2 leading-7 text-violet-100/70">Pay by bank transfer, JazzCash or Easypaisa using the account details supplied by HAZA-SMS administration, then upload proof here.</p>{pendingPayment?<div className="mt-6 rounded-2xl border border-amber-300/25 bg-amber-300/10 p-4 text-amber-100">A receipt is already pending review. You do not need to submit it again.</div>:<form onSubmit={submit} className="mt-6 grid gap-4"><label className="grid gap-2 text-sm font-bold">Plan<select name="plan" defaultValue={subscription.plan==="yearly"?"yearly":"monthly"} className="rounded-xl border border-white/15 bg-purple-950 p-3"><option value="monthly">Monthly — Rs. 5,000</option><option value="yearly">Yearly — Rs. 50,000</option></select></label><label className="grid gap-2 text-sm font-bold">Payment method<select name="paymentMethod" className="rounded-xl border border-white/15 bg-purple-950 p-3"><option value="bank">Bank transfer</option><option value="jazzcash">JazzCash</option><option value="easypaisa">Easypaisa</option></select></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Payer name<input name="payerName" required maxLength={100} className="rounded-xl border border-white/15 bg-white/10 p-3" /></label><label className="grid gap-2 text-sm font-bold">Transaction reference<input name="paymentReference" required maxLength={120} className="rounded-xl border border-white/15 bg-white/10 p-3" /></label></div><label className="grid gap-2 text-sm font-bold">Receipt image or PDF<input name="receipt" type="file" required accept="image/jpeg,image/png,image/webp,application/pdf" className="rounded-xl border border-dashed border-white/25 bg-white/5 p-4" /><small className="font-normal text-violet-200/65">JPEG, PNG, WebP or PDF up to 8 MB.</small></label>{message?<p role="status" className="rounded-xl bg-white/10 p-3 text-sm">{message}</p>:null}<button disabled={busy} className="min-h-12 rounded-xl bg-gradient-to-r from-violet-500 to-fuchsia-600 font-black disabled:opacity-60">{busy?"Uploading receipt…":"Submit receipt for approval"}</button></form>}</article></section>
    </div>
  </main>;
}
