import { env } from "cloudflare:workers";
import { authorize } from "../../../../lib/authorization";
import { parseCsv } from "../../../../lib/csv";
import { enforceRateLimit, requireSameOrigin } from "../../../../lib/security";

export const dynamic="force-dynamic";
const date=/^\d{4}-\d{2}-\d{2}$/;
const allowedHeaders=new Set(["admission_number","first_name","last_name","preferred_name","gender","date_of_birth","blood_group","nationality","religion","national_id","place_of_birth","mother_tongue","domicile_district","identity_mark","admission_category","admission_source","previous_admission_number","phone","email","address_line1","address_line2","city","province","postal_code","emergency_contact_name","emergency_contact_phone","emergency_contact_relation","allergies","dietary_requirements","special_needs","accessibility_notes","doctor_name","doctor_phone","vaccination_notes","medical_notes","previous_school","previous_class","profile_notes","enrollment_status","admitted_on","campus_code","campus_name","academic_year","class_code","class_name","section_code","section_name","roll_number"]);
const get=(row:Record<string,string>,key:string,length=300)=>(row[key]??"").trim().slice(0,length);
export async function POST(request:Request){
  const sameOrigin=requireSameOrigin(request);if(sameOrigin)return sameOrigin;const auth=await authorize("students.import");if(!auth)return Response.json({error:"You do not have permission to import students."},{status:403});if(!await enforceRateLimit(auth,"student.bulk_import",10,600))return Response.json({error:"Import limit reached. Try again later."},{status:429});
  const data=await request.formData(),file=data.get("file"),mode=String(data.get("mode")??"validate");if(!(file instanceof File)||file.size<1||file.size>2*1024*1024||!file.name.toLowerCase().endsWith(".csv"))return Response.json({error:"Choose a CSV file up to 2 MB."},{status:400});
  const parsed=parseCsv(await file.text());if(parsed.length<2)return Response.json({error:"The CSV must include a header and at least one student."},{status:400});if(parsed.length>401)return Response.json({error:"Import a maximum of 400 students at one time."},{status:400});
  const headers=parsed[0].map(v=>v.toLowerCase().replace(/\s+/g,"_"));if(new Set(headers).size!==headers.length||headers.some(h=>!allowedHeaders.has(h)))return Response.json({error:"The CSV contains duplicate or unsupported columns.",supported:[...allowedHeaders]},{status:400});if(!headers.includes("first_name")||!headers.includes("campus_code"))return Response.json({error:"first_name and campus_code columns are required."},{status:400});
  const [campuses,classes,sections,years,existing]=await Promise.all([env.DB.prepare("SELECT id,upper(code) code FROM campuses WHERE organization_id=?1 AND status='active'").bind(auth.organizationId).all<{id:string;code:string}>(),env.DB.prepare("SELECT id,campus_id,upper(code) code FROM classes WHERE organization_id=?1 AND status='active'").bind(auth.organizationId).all<{id:string;campus_id:string|null;code:string}>(),env.DB.prepare("SELECT id,campus_id,class_id,upper(code) code FROM sections WHERE organization_id=?1 AND status='active'").bind(auth.organizationId).all<{id:string;campus_id:string;class_id:string;code:string}>(),env.DB.prepare("SELECT id,lower(name) name,is_current FROM academic_years WHERE organization_id=?1").bind(auth.organizationId).all<{id:string;name:string;is_current:number}>(),env.DB.prepare("SELECT upper(admission_number) admission_number FROM students WHERE organization_id=?1").bind(auth.organizationId).all<{admission_number:string}>()]);
  const campusMap=new Map(campuses.results.map(v=>[v.code,v.id])),existingNumbers=new Set(existing.results.map(v=>v.admission_number)),seen=new Set<string>(),validRows:{row:number;data:Record<string,string>;campusId:string;classId:string|null;sectionId:string|null;yearId:string|null;admissionNumber:string}[]=[],errors:{row:number;field:string;message:string}[]=[];
  parsed.slice(1).forEach((values,index)=>{const rowNumber=index+2,row=Object.fromEntries(headers.map((h,i)=>[h,(values[i]??"").trim()])),first=get(row,"first_name",80),campusCode=get(row,"campus_code",40).toUpperCase(),campusId=campusMap.get(campusCode),gender=get(row,"gender",20).toLowerCase(),dob=get(row,"date_of_birth",10),admitted=get(row,"admitted_on",10),email=get(row,"email",160),classCode=get(row,"class_code",40).toUpperCase(),sectionCode=get(row,"section_code",40).toUpperCase(),yearName=get(row,"academic_year",80).toLowerCase();let admissionNumber=get(row,"admission_number",40).toUpperCase();
    if(!first)errors.push({row:rowNumber,field:"first_name",message:"First name is required."});if(!campusId)errors.push({row:rowNumber,field:"campus_code",message:`Campus code ${campusCode||"is missing"} was not found.`});if(gender&&!['male','female','other'].includes(gender))errors.push({row:rowNumber,field:"gender",message:"Use male, female or other."});if(dob&&!date.test(dob))errors.push({row:rowNumber,field:"date_of_birth",message:"Use YYYY-MM-DD."});if(admitted&&!date.test(admitted))errors.push({row:rowNumber,field:"admitted_on",message:"Use YYYY-MM-DD."});if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))errors.push({row:rowNumber,field:"email",message:"Email is invalid."});
    if(!admissionNumber)admissionNumber=`IMP-${Date.now().toString(36).toUpperCase()}-${rowNumber}`;if(existingNumbers.has(admissionNumber)||seen.has(admissionNumber))errors.push({row:rowNumber,field:"admission_number",message:"Admission number already exists."});seen.add(admissionNumber);
    const schoolClass=classCode?classes.results.find(v=>v.code===classCode&&(!v.campus_id||v.campus_id===campusId)):null;if(classCode&&!schoolClass)errors.push({row:rowNumber,field:"class_code",message:"Class code is not valid for this campus."});const section=sectionCode&&schoolClass?sections.results.find(v=>v.code===sectionCode&&v.campus_id===campusId&&v.class_id===schoolClass.id):null;if(sectionCode&&!section)errors.push({row:rowNumber,field:"section_code",message:"Section code is not valid for this class."});const year=yearName?years.results.find(v=>v.name===yearName):years.results.find(v=>v.is_current);if((classCode||sectionCode)&&!year)errors.push({row:rowNumber,field:"academic_year",message:"Academic year was not found and no current year is set."});
    validRows.push({row:rowNumber,data:row,campusId:campusId??"",classId:schoolClass?.id??null,sectionId:section?.id??null,yearId:year?.id??null,admissionNumber});
  });
  if(mode!=="commit"||errors.length)return Response.json({ok:errors.length===0,mode:"validation",total:validRows.length,valid:validRows.length-new Set(errors.map(e=>e.row)).size,invalid:new Set(errors.map(e=>e.row)).size,errors:errors.slice(0,200)});
  const statements=[];for(const item of validRows){const r=item.data,id=crypto.randomUUID();statements.push(env.DB.prepare(`INSERT INTO students (id,organization_id,home_campus_id,admission_number,first_name,last_name,preferred_name,gender,date_of_birth,blood_group,nationality,religion,national_id,place_of_birth,mother_tongue,domicile_district,identity_mark,admission_category,admission_source,previous_admission_number,phone,email,address_line1,address_line2,city,province,postal_code,emergency_contact_name,emergency_contact_phone,emergency_contact_relation,allergies,dietary_requirements,special_needs,accessibility_notes,doctor_name,doctor_phone,vaccination_notes,medical_notes,previous_school,previous_class,profile_notes,enrollment_status,admitted_on) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18,?19,?20,?21,?22,?23,?24,?25,?26,?27,?28,?29,?30,?31,?32,?33,?34,?35,?36,?37,?38,?39,?40,?41,'active',?42)`).bind(id,auth.organizationId,item.campusId,item.admissionNumber,get(r,"first_name",80),get(r,"last_name",80)||null,get(r,"preferred_name",80)||null,get(r,"gender",20)||null,get(r,"date_of_birth",10)||null,get(r,"blood_group",10)||null,get(r,"nationality",60)||null,get(r,"religion",60)||null,get(r,"national_id",40)||null,get(r,"place_of_birth",100)||null,get(r,"mother_tongue",60)||null,get(r,"domicile_district",100)||null,get(r,"identity_mark",160)||null,get(r,"admission_category",60)||null,get(r,"admission_source",100)||null,get(r,"previous_admission_number",40)||null,get(r,"phone",30)||null,get(r,"email",160)||null,get(r,"address_line1")||null,get(r,"address_line2")||null,get(r,"city",80)||null,get(r,"province",80)||null,get(r,"postal_code",20)||null,get(r,"emergency_contact_name",120)||null,get(r,"emergency_contact_phone",30)||null,get(r,"emergency_contact_relation",40)||null,get(r,"allergies",500)||null,get(r,"dietary_requirements",500)||null,get(r,"special_needs",500)||null,get(r,"accessibility_notes",500)||null,get(r,"doctor_name",120)||null,get(r,"doctor_phone",30)||null,get(r,"vaccination_notes",500)||null,get(r,"medical_notes",1000)||null,get(r,"previous_school",160)||null,get(r,"previous_class",80)||null,get(r,"profile_notes",1000)||null,get(r,"admitted_on",10)||null));if(item.classId&&item.yearId)statements.push(env.DB.prepare("INSERT INTO enrollments (id,organization_id,student_id,academic_year_id,campus_id,class_id,section_id,roll_number,status,enrolled_on) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,'active',?9)").bind(crypto.randomUUID(),auth.organizationId,id,item.yearId,item.campusId,item.classId,item.sectionId,get(r,"roll_number",40)||null,get(r,"admitted_on",10)||new Date().toISOString().slice(0,10)));}
  statements.push(env.DB.prepare("INSERT INTO audit_logs (id,organization_id,actor_user_id,action,entity_type,outcome,metadata_json) VALUES (?1,?2,?3,'student.bulk_import','students','success',?4)").bind(crypto.randomUUID(),auth.organizationId,auth.userId,JSON.stringify({count:validRows.length,file:file.name.slice(0,120)})));try{await env.DB.batch(statements);return Response.json({ok:true,mode:"commit",imported:validRows.length});}catch{return Response.json({error:"The import could not be completed; the validated batch was not applied."},{status:409});}
}
