import { env } from "cloudflare:workers";
import { authorize } from "../../../../../lib/authorization";
import { enforceRateLimit, requireSameOrigin, safeMetadata } from "../../../../../lib/security";

export const dynamic="force-dynamic";
const clean=(value:unknown,length=600)=>typeof value==="string"?value.trim().slice(0,length):"";

export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){
  const sameOrigin=requireSameOrigin(request);if(sameOrigin)return sameOrigin;
  const {id}=await params,body=await request.json().catch(()=>null) as Record<string,unknown>|null,action=clean(body?.action,30);
  const permission=action==="assign_fee"?"admissions.assign_fee":action==="enroll"?"admissions.enroll":"admissions.approve",auth=await authorize(permission);if(!auth)return Response.json({error:"You do not have permission to complete this admission action."},{status:403});
  if(!await enforceRateLimit(auth,`admission.${action}`,30,300))return Response.json({error:"Admission action limit reached. Try again later."},{status:429});
  const application=await env.DB.prepare("SELECT * FROM admission_applications WHERE id=?1 AND organization_id=?2").bind(id,auth.organizationId).first<Record<string,unknown>>();if(!application)return Response.json({error:"Application not found."},{status:404});
  if(action==="assign_fee"){
    const feePackageId=clean(body?.feePackageId),discountAmount=Math.max(0,Math.round(Number(body?.discountAmount)||0)),discountReason=clean(body?.discountReason,300),notes=clean(body?.notes,500);
    const fee=await env.DB.prepare(`SELECT id,admission_fee+registration_fee+security_deposit+annual_charges total FROM admission_fee_packages WHERE id=?1 AND organization_id=?2 AND status='active' AND (campus_id IS NULL OR campus_id=?3) AND (class_id IS NULL OR class_id=?4)`).bind(feePackageId,auth.organizationId,application.campus_id,application.applying_class_id).first<{id:string;total:number}>();if(!fee)return Response.json({error:"Select a fee package available for this campus and class."},{status:400});
    if(discountAmount>fee.total)return Response.json({error:"Discount cannot exceed the initial package charges."},{status:400});
    const assignmentId=crypto.randomUUID();await env.DB.batch([
      env.DB.prepare(`INSERT INTO application_fee_assignments (id,organization_id,application_id,fee_package_id,discount_amount,discount_reason,notes,assigned_by) VALUES (?1,?2,?3,?4,?5,?6,?7,?8) ON CONFLICT(application_id) DO UPDATE SET fee_package_id=excluded.fee_package_id,discount_amount=excluded.discount_amount,discount_reason=excluded.discount_reason,notes=excluded.notes,assigned_by=excluded.assigned_by,updated_at=unixepoch()*1000`).bind(assignmentId,auth.organizationId,id,feePackageId,discountAmount,discountReason||null,notes||null,auth.userId),
      env.DB.prepare("INSERT INTO audit_logs (id,organization_id,campus_id,actor_user_id,action,entity_type,entity_id,outcome,metadata_json) VALUES (?1,?2,?3,?4,'admission.fee.assign','admission_application',?5,'success',?6)").bind(crypto.randomUUID(),auth.organizationId,application.campus_id,auth.userId,id,safeMetadata({feePackageId,discountAmount})),
    ]);return Response.json({ok:true});
  }
  if(action==="approve"||action==="reject"){
    const notes=clean(body?.notes,600);if(application.status!=="submitted"&&application.status!=="approved")return Response.json({error:"Only submitted applications can receive an admission decision."},{status:409});
    if(action==="approve"){
      const assignment=await env.DB.prepare("SELECT id FROM application_fee_assignments WHERE application_id=?1 AND organization_id=?2").bind(id,auth.organizationId).first();if(!assignment)return Response.json({error:"Assign a fee package before approving the application."},{status:400});
      const blocked=await env.DB.prepare("SELECT count(*) value FROM admission_documents WHERE application_id=?1 AND organization_id=?2 AND verification_status='rejected'").bind(id,auth.organizationId).first<{value:number}>();if((blocked?.value??0)>0)return Response.json({error:"Resolve rejected documents before approval."},{status:400});
    }
    const status=action==="approve"?"approved":"rejected";await env.DB.batch([
      env.DB.prepare("UPDATE admission_applications SET status=?1,decision_notes=?2,decided_by=?3,decided_at=?4,updated_at=unixepoch()*1000 WHERE id=?5 AND organization_id=?6").bind(status,notes||null,auth.userId,Date.now(),id,auth.organizationId),
      env.DB.prepare("INSERT INTO audit_logs (id,organization_id,campus_id,actor_user_id,action,entity_type,entity_id,outcome,metadata_json) VALUES (?1,?2,?3,?4,?5,'admission_application',?6,'success',?7)").bind(crypto.randomUUID(),auth.organizationId,application.campus_id,auth.userId,`admission.application.${status}`,id,safeMetadata({notes})),
    ]);return Response.json({ok:true,status});
  }
  if(action!=="enroll")return Response.json({error:"Invalid admission action."},{status:400});
  if(application.status!=="approved"||application.student_id)return Response.json({error:"Only an approved, unconverted application can become a student."},{status:409});
  if(!application.academic_year_id||!application.applying_class_id)return Response.json({error:"Academic year and class are required before enrollment."},{status:400});
  const feeAssignment=await env.DB.prepare("SELECT id FROM application_fee_assignments WHERE application_id=?1 AND organization_id=?2").bind(id,auth.organizationId).first();if(!feeAssignment)return Response.json({error:"Fee package assignment is required."},{status:400});
  const sectionId=clean(body?.sectionId),enrolledOn=clean(body?.enrolledOn,10)||new Date().toISOString().slice(0,10),rollNumber=clean(body?.rollNumber,30);
  if(!/^\d{4}-\d{2}-\d{2}$/.test(enrolledOn))return Response.json({error:"Enter a valid enrollment date."},{status:400});
  if(sectionId){const section=await env.DB.prepare("SELECT id FROM sections WHERE id=?1 AND organization_id=?2 AND campus_id=?3 AND class_id=?4 AND status='active'").bind(sectionId,auth.organizationId,application.campus_id,application.applying_class_id).first();if(!section)return Response.json({error:"Select a valid section for the application class."},{status:400});}
  const duplicate=await env.DB.prepare("SELECT id FROM students WHERE organization_id=?1 AND ((date_of_birth=?2 AND lower(first_name)=lower(?3) AND lower(coalesce(last_name,''))=lower(?4)) OR admission_number=?5) LIMIT 1").bind(auth.organizationId,application.date_of_birth,application.child_first_name,application.child_last_name??"",`TMS-${String(application.application_number).replace(/^APP-/,"")}`).first();if(duplicate)return Response.json({error:"A matching student record already exists. Review it before converting."},{status:409});
  const existingGuardian=await env.DB.prepare("SELECT id,family_id FROM guardians WHERE organization_id=?1 AND ((?2<>'' AND national_id=?2) OR primary_phone=?3) LIMIT 1").bind(auth.organizationId,application.guardian_national_id??"",application.primary_phone).first<{id:string;family_id:string|null}>();
  const studentId=crypto.randomUUID(),enrollmentId=crypto.randomUUID(),familyId=existingGuardian?.family_id??crypto.randomUUID(),guardianId=existingGuardian?.id??crypto.randomUUID(),admissionNumber=`TMS-${String(application.application_number).replace(/^APP-/,"")}`;
  const nameParts=String(application.guardian_name).trim().split(/\s+/),guardianFirst=nameParts.shift()||"Guardian",guardianLast=nameParts.join(" ")||null;
  const docs=await env.DB.prepare("SELECT d.*,a.asset_type FROM admission_documents d JOIN storage_assets a ON a.id=d.asset_id WHERE d.application_id=?1 AND d.organization_id=?2 AND d.verification_status='verified'").bind(id,auth.organizationId).all<Record<string,unknown>>(),photo=docs.results.find(v=>v.document_type==="student_photo");
  const statements=[
    env.DB.prepare("INSERT INTO students (id,organization_id,home_campus_id,admission_number,first_name,last_name,gender,date_of_birth,phone,email,address_line1,city,emergency_contact_name,emergency_contact_phone,emergency_contact_relation,medical_notes,special_needs,previous_school,previous_class,enrollment_status,photo_asset_id,admitted_on,admission_source) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16,?17,?18,?19,'active',?20,?21,'admission_application')").bind(studentId,auth.organizationId,application.campus_id,admissionNumber,application.child_first_name,application.child_last_name,application.gender,application.date_of_birth,application.primary_phone,application.email,application.address,application.city,application.guardian_name,application.primary_phone,application.guardian_relationship,application.medical_notes,application.special_needs,application.previous_school,application.previous_class,photo?.asset_id??null,enrolledOn),
    env.DB.prepare("INSERT INTO enrollments (id,organization_id,student_id,academic_year_id,campus_id,class_id,section_id,roll_number,status,enrolled_on) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,'active',?9)").bind(enrollmentId,auth.organizationId,studentId,application.academic_year_id,application.campus_id,application.applying_class_id,sectionId||null,rollNumber||null,enrolledOn),
    env.DB.prepare("INSERT INTO enrollment_events (id,organization_id,student_id,enrollment_id,event_type,to_campus_id,to_class_id,effective_on,reason,performed_by) VALUES (?1,?2,?3,?4,'admitted',?5,?6,?7,'Approved admission application',?8)").bind(crypto.randomUUID(),auth.organizationId,studentId,enrollmentId,application.campus_id,application.applying_class_id,enrolledOn,auth.userId),
    env.DB.prepare("UPDATE admission_applications SET status='enrolled',student_id=?1,converted_by=?2,converted_at=?3,updated_at=unixepoch()*1000 WHERE id=?4 AND organization_id=?5 AND status='approved' AND student_id IS NULL").bind(studentId,auth.userId,Date.now(),id,auth.organizationId),
    env.DB.prepare("INSERT INTO audit_logs (id,organization_id,campus_id,actor_user_id,action,entity_type,entity_id,outcome,metadata_json) VALUES (?1,?2,?3,?4,'admission.application.enroll','student',?5,'success',?6)").bind(crypto.randomUUID(),auth.organizationId,application.campus_id,auth.userId,studentId,safeMetadata({applicationId:id,admissionNumber,enrollmentId})),
  ];
  if(!existingGuardian?.family_id)statements.push(env.DB.prepare("INSERT INTO families (id,organization_id,family_code,family_name,address,city) VALUES (?1,?2,?3,?4,?5,?6)").bind(familyId,auth.organizationId,`FAM-${String(application.application_number).slice(-8)}`,`${application.guardian_name} Family`,application.address,application.city));
  if(existingGuardian&&!existingGuardian.family_id)statements.push(env.DB.prepare("UPDATE guardians SET family_id=?1,updated_at=unixepoch()*1000 WHERE id=?2 AND organization_id=?3 AND family_id IS NULL").bind(familyId,guardianId,auth.organizationId));
  if(!existingGuardian)statements.push(env.DB.prepare("INSERT INTO guardians (id,organization_id,family_id,first_name,last_name,national_id,occupation,primary_phone,alternate_phone,email,address,city) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12)").bind(guardianId,auth.organizationId,familyId,guardianFirst,guardianLast,application.guardian_national_id,application.guardian_occupation,application.primary_phone,application.alternate_phone,application.email,application.address,application.city));
  statements.push(env.DB.prepare("INSERT INTO student_guardians (student_id,guardian_id,relationship,is_primary,lives_with_student,legal_guardian,pickup_authorized,receives_academic,receives_financial) VALUES (?1,?2,?3,1,1,1,1,1,1)").bind(studentId,guardianId,application.guardian_relationship||"Guardian"));
  for(const doc of docs.results)statements.push(env.DB.prepare("INSERT INTO student_documents (id,organization_id,student_id,asset_id,document_type,title,status,verification_status,is_required,verified_by,verified_at) VALUES (?1,?2,?3,?4,?5,?6,'active','verified',0,?7,?8)").bind(crypto.randomUUID(),auth.organizationId,studentId,doc.asset_id,doc.document_type,doc.title,doc.verified_by,doc.verified_at));
  try{await env.DB.batch(statements);return Response.json({ok:true,studentId,admissionNumber});}catch{return Response.json({error:"The application changed during conversion. Refresh and try again."},{status:409});}
}
