import { env } from "cloudflare:workers";
import { authorize, requireCampusAccess } from "../../../lib/authorization";
import { enforceRateLimit, requireSameOrigin, safeMetadata } from "../../../lib/security";
export const dynamic="force-dynamic";
const clean=(v:unknown,n=160)=>typeof v==="string"?v.trim().slice(0,n):"";
const date=(v:string)=>!v||/^\d{4}-\d{2}-\d{2}$/.test(v);

export async function GET(request:Request){
  const auth=await authorize("staff.view");if(!auth)return Response.json({error:"You do not have permission to view staff."},{status:403});
  const u=new URL(request.url),search=clean(u.searchParams.get("search"),80),requestedCampusId=clean(u.searchParams.get("campusId")),campusId=requestedCampusId||(!auth.organizationWide?auth.activeCampusId??"":""),status=clean(u.searchParams.get("status"),20),category=clean(u.searchParams.get("category"),30);
  if(campusId){const denied=await requireCampusAccess(auth,campusId,"staff.list");if(denied)return denied;}
  const [rows,total,active,teaching,nonTeaching]=await Promise.all([
    env.DB.prepare(`SELECT s.id,s.employee_number,s.first_name,s.last_name,s.preferred_name,s.phone,s.email,s.designation,s.department,s.staff_category,s.employment_type,s.joined_on,s.status,s.photo_asset_id,c.name campus_name FROM staff s JOIN campuses c ON c.id=s.campus_id WHERE s.organization_id=?1 AND (?2='' OR s.campus_id=?2) AND (?3='' OR s.status=?3) AND (?4='' OR s.staff_category=?4) AND (?5='' OR s.first_name LIKE '%'||?5||'%' OR coalesce(s.last_name,'') LIKE '%'||?5||'%' OR s.employee_number LIKE '%'||?5||'%' OR s.phone LIKE '%'||?5||'%' OR s.designation LIKE '%'||?5||'%') ORDER BY CASE s.status WHEN 'active' THEN 0 ELSE 1 END,s.first_name,s.last_name LIMIT 150`).bind(auth.organizationId,campusId,status,category,search).all(),
    env.DB.prepare("SELECT count(*) value FROM staff WHERE organization_id=?1 AND (?2='' OR campus_id=?2)").bind(auth.organizationId,campusId).first<{value:number}>(),env.DB.prepare("SELECT count(*) value FROM staff WHERE organization_id=?1 AND status='active' AND (?2='' OR campus_id=?2)").bind(auth.organizationId,campusId).first<{value:number}>(),env.DB.prepare("SELECT count(*) value FROM staff WHERE organization_id=?1 AND status='active' AND staff_category='teaching' AND (?2='' OR campus_id=?2)").bind(auth.organizationId,campusId).first<{value:number}>(),env.DB.prepare("SELECT count(*) value FROM staff WHERE organization_id=?1 AND status='active' AND staff_category='non_teaching' AND (?2='' OR campus_id=?2)").bind(auth.organizationId,campusId).first<{value:number}>(),
  ]);
  return Response.json({staff:rows.results,summary:{total:total?.value??0,active:active?.value??0,teaching:teaching?.value??0,nonTeaching:nonTeaching?.value??0},canViewFinancial:auth.permissions.has("staff.financial")},{headers:{"cache-control":"private, no-store"}});
}

export async function POST(request:Request){
  const origin=requireSameOrigin(request);if(origin)return origin;const auth=await authorize("staff.create");if(!auth)return Response.json({error:"You do not have permission to create staff records."},{status:403});if(!await enforceRateLimit(auth,"staff.create",40,300))return Response.json({error:"Staff creation limit reached."},{status:429});
  const b=await request.json().catch(()=>null) as Record<string,unknown>|null,campusId=clean(b?.campusId),firstName=clean(b?.firstName,80),lastName=clean(b?.lastName,80),phone=clean(b?.phone,30),email=clean(b?.email,160).toLowerCase(),designation=clean(b?.designation,100),department=clean(b?.department,100),category=clean(b?.staffCategory,30)||"teaching",employmentType=clean(b?.employmentType,30)||"full_time",joinedOn=clean(b?.joinedOn,10),employeeNumber=clean(b?.employeeNumber,40);
  if(!campusId||!firstName||!phone||!designation||!date(joinedOn)||!joinedOn||!['teaching','non_teaching','management','support'].includes(category)||!['full_time','part_time','contract','visiting','intern'].includes(employmentType)||email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return Response.json({error:"Complete the required staff information."},{status:400});
  const campus=await env.DB.prepare("SELECT code FROM campuses WHERE id=?1 AND organization_id=?2 AND status='active'").bind(campusId,auth.organizationId).first<{code:string}>();if(!campus)return Response.json({error:"Select a valid campus."},{status:400});
  const denied=await requireCampusAccess(auth,campusId,"staff.create");if(denied)return denied;
  const id=crypto.randomUUID(),count=await env.DB.prepare("SELECT count(*) value FROM staff WHERE organization_id=?1").bind(auth.organizationId).first<{value:number}>(),number=employeeNumber||`EMP-${campus.code.toUpperCase()}-${String((count?.value??0)+1).padStart(4,'0')}`;
  try{await env.DB.batch([env.DB.prepare("INSERT INTO staff (id,organization_id,campus_id,employee_number,first_name,last_name,phone,email,designation,department,staff_category,employment_type,joined_on,status,created_by) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,'active',?14)").bind(id,auth.organizationId,campusId,number,firstName,lastName||null,phone,email||null,designation,department||null,category,employmentType,joinedOn,auth.userId),env.DB.prepare("INSERT INTO audit_logs (id,organization_id,campus_id,actor_user_id,action,entity_type,entity_id,outcome,metadata_json) VALUES (?1,?2,?3,?4,'staff.create','staff',?5,'success',?6)").bind(crypto.randomUUID(),auth.organizationId,campusId,auth.userId,id,safeMetadata({employeeNumber:number}))]);return Response.json({ok:true,id,employeeNumber:number});}catch{return Response.json({error:"Employee number already exists."},{status:409});}
}
