import { env } from "cloudflare:workers";
import { authorize } from "../../../lib/authorization";

export const dynamic = "force-dynamic";
export async function GET(request:Request){
  const auth=await authorize("portal.view");if(!auth)return Response.json({error:"You do not have permission to open a family or student portal."},{status:403});
  const roles=await env.DB.prepare("SELECT DISTINCT r.key FROM membership_roles mr JOIN roles r ON r.id=mr.role_id WHERE mr.membership_id=?1 AND r.key IN ('parent','student','principal','school_administrator','super_administrator')").bind(auth.membershipId).all<{key:string}>(),roleSet=new Set(roles.results.map(v=>v.key)),isParent=roleSet.has("parent"),isStudent=roleSet.has("student"),isAdmin=["principal","school_administrator","super_administrator"].some(v=>roleSet.has(v));
  const links=isParent?await env.DB.prepare("SELECT DISTINCT s.id,s.admission_number,s.first_name,s.last_name,s.home_campus_id FROM guardians g JOIN student_guardians sg ON sg.guardian_id=g.id JOIN students s ON s.id=sg.student_id AND s.organization_id=g.organization_id WHERE g.organization_id=?1 AND lower(g.email)=lower(?2) AND g.status='active' AND s.enrollment_status='active' ORDER BY s.first_name,s.last_name").bind(auth.organizationId,auth.email).all<Record<string,unknown>>():isStudent?await env.DB.prepare("SELECT id,admission_number,first_name,last_name,home_campus_id FROM students WHERE organization_id=?1 AND lower(email)=lower(?2) AND enrollment_status='active'").bind(auth.organizationId,auth.email).all<Record<string,unknown>>():await env.DB.prepare("SELECT id,admission_number,first_name,last_name,home_campus_id FROM students WHERE organization_id=?1 AND enrollment_status='active' ORDER BY first_name,last_name LIMIT 100").bind(auth.organizationId).all<Record<string,unknown>>();
  const requested=new URL(request.url).searchParams.get("studentId"),studentId=requested&&links.results.some(v=>v.id===requested)?requested:String(links.results[0]?.id||"");
  if(!studentId)return Response.json({portalRole:isParent?"parent":isStudent?"student":"administrator",students:links.results,student:null,attendance:{summary:null,records:[]},fees:[],results:[],assignments:[],resources:[],announcements:[],notifications:[]},{headers:{"cache-control":"private, no-store"}});
  const student=await env.DB.prepare("SELECT s.id,s.admission_number,s.first_name,s.last_name,s.preferred_name,s.photo_asset_id,e.roll_number,e.class_id,e.section_id,e.campus_id,e.academic_year_id,c.name campus_name,cl.name class_name,se.name section_name,y.name academic_year_name FROM students s JOIN enrollments e ON e.student_id=s.id AND e.organization_id=s.organization_id AND e.status='active' JOIN campuses c ON c.id=e.campus_id LEFT JOIN classes cl ON cl.id=e.class_id LEFT JOIN sections se ON se.id=e.section_id JOIN academic_years y ON y.id=e.academic_year_id WHERE s.id=?1 AND s.organization_id=?2").bind(studentId,auth.organizationId).first<Record<string,unknown>>();
  if(!student)return Response.json({error:"The selected student has no active enrollment."},{status:404});
  const [attendanceSummary,attendanceRecords,fees,results,assignments,resources,announcements,notifications]=await Promise.all([
    env.DB.prepare("SELECT count(*) total_days,sum(CASE WHEN status='present' THEN 1 ELSE 0 END) present_days,sum(CASE WHEN status='absent' THEN 1 ELSE 0 END) absent_days,sum(CASE WHEN status='late' THEN 1 ELSE 0 END) late_days,round(100.0*sum(CASE WHEN status IN ('present','late') THEN 1 ELSE 0 END)/nullif(count(*),0),1) attendance_rate FROM student_attendance_records WHERE organization_id=?1 AND student_id=?2").bind(auth.organizationId,studentId).first(),
    env.DB.prepare("SELECT r.attendance_date,r.status,r.remarks FROM student_attendance_records r WHERE r.organization_id=?1 AND r.student_id=?2 ORDER BY r.attendance_date DESC LIMIT 30").bind(auth.organizationId,studentId).all(),
    env.DB.prepare("SELECT id,invoice_number,billing_month,due_on,total_amount,paid_amount,balance_amount,status FROM fee_invoices WHERE organization_id=?1 AND student_id=?2 ORDER BY due_on DESC LIMIT 50").bind(auth.organizationId,studentId).all(),
    env.DB.prepare("SELECT a.id,a.title,a.assessment_date,a.maximum_marks,m.obtained_marks,m.percentage,m.grade_label,m.is_passing,m.is_absent,sub.name subject_name FROM assessments a JOIN assessment_marks m ON m.assessment_id=a.id AND m.organization_id=a.organization_id JOIN subjects sub ON sub.id=a.subject_id WHERE a.organization_id=?1 AND m.student_id=?2 AND a.status='published' ORDER BY a.assessment_date DESC LIMIT 50").bind(auth.organizationId,studentId).all(),
    env.DB.prepare("SELECT a.id,a.title,a.instructions,a.assigned_on,a.due_at,a.max_points,a.status,s.name subject_name,(SELECT count(*) FROM assignment_resources ar WHERE ar.assignment_id=a.id) resource_count FROM assignments a JOIN subjects s ON s.id=a.subject_id WHERE a.organization_id=?1 AND a.status='published' AND a.class_id=?2 AND (a.section_id IS NULL OR a.section_id=?3) ORDER BY a.due_at IS NULL,a.due_at LIMIT 100").bind(auth.organizationId,student.class_id,student.section_id).all(),
    env.DB.prepare("SELECT r.id,r.title,r.description,r.resource_type,r.external_url,s.name subject_name FROM learning_resources r LEFT JOIN subjects s ON s.id=r.subject_id WHERE r.organization_id=?1 AND r.status='published' AND (r.campus_id IS NULL OR r.campus_id=?2) AND (r.class_id IS NULL OR r.class_id=?3) AND (r.section_id IS NULL OR r.section_id=?4) ORDER BY r.published_at DESC LIMIT 100").bind(auth.organizationId,student.campus_id,student.class_id,student.section_id).all(),
    env.DB.prepare("SELECT id,title,body,priority,published_at,expires_at FROM communication_announcements WHERE organization_id=?1 AND status='published' AND (campus_id IS NULL OR campus_id=?2) AND audience IN ('all',?3) AND (expires_at IS NULL OR expires_at>?4) ORDER BY published_at DESC LIMIT 50").bind(auth.organizationId,student.campus_id,isParent?"parents":"students",Date.now()).all(),
    env.DB.prepare("SELECT id,event_code,title,body,read_at,created_at FROM user_notifications WHERE organization_id=?1 AND user_id=?2 ORDER BY read_at IS NULL DESC,created_at DESC LIMIT 50").bind(auth.organizationId,auth.userId).all(),
  ]);
  return Response.json({portalRole:isParent?"parent":isStudent?"student":isAdmin?"administrator":"viewer",students:links.results,student,attendance:{summary:attendanceSummary||{},records:attendanceRecords.results},fees:fees.results,results:results.results,assignments:assignments.results,resources:resources.results,announcements:announcements.results,notifications:notifications.results},{headers:{"cache-control":"private, no-store"}});
}
